<?php
$manual[11] = '<p>Nem todos os utilizadores podem perceber apropriadamente os conteúdos não textuais, seja porque têm alguma deficiência ou porque os seus equipamentos ou conexões lhes limitam essa percepção. Por esta razão, o ponto solicita que, para todo o conteúdo que não seja texto, se disponibilize também uma alternativa em formato texto mediante a linguagem de programação ou das técnicas existentes para o efeito.</p>
<p>As técnicas para proporcionar um conteúdo alternativo varía segundo cada elemento. Pode requerer o uso de atributos específicos, como "alt" ou "longdesc"; ou pelo uso de outros elementos (&lt;script&gt;/&lt;noscript&gt;, por exemplo) ou a inclusão dos textos alternativos dentro da própria função codificada, como é o caso de &lt;applet&gt; ou &lt;iframe&gt;.</p>';
$manual[12] = '<p>Um mapa de imagem define zonas activas num elemento &lt;img&gt; ou &lt;input&gt;, de modo que é possível associar uma acção a cada uma dessas zonas (tipicamente activar um <span lang="en" xml:lang="en">link</span>).</p>
<p>Nos mapas de imagem do tipo servidor, quando o utilizador activa um <span lang="en" xml:lang="en">link</span> utilizando o rato, as coordenadas do ponteiro do rato sobre o ecrã é enviado ao servidor onde se encontra o arquivo com a definição do mapa.</p>
<p>Como é necessário um dispositivo de entrada específico (um rato), deve-se disponibilizar informação redundante criando uma lista no formato texto de todos os vínculos definidos no mapa, por forma a que possam ser activados também através do teclado.</p>';
$manual[13] = '<p>As apresentações de vídeo ou animação devem dispôr de uma descrição sonora de, por exemplo, os cenários, os gráficos que se apresentam, as acções, etcétera, para os utilizadores cegos ou com baixa visão.</p>';
$manual[14] = '<p>Oferecer um equivalente textual ou uma descrição separados de uma apresentação multimédia não proporcionam a mesma experiência às pessoas surdas ou com dificuldades auditivas, nem às pessoas que desconhecem o idioma original da apresentação.</p>
<p>Por esta razão devem-se incluir equivalentes alternativos sincronizados com a apresentação. Estes são úteis não apenas para as pessoas surdas ou dificuldades auditivas, mas também para quem trabalhar num ambiente silencioso (uma biblioteca, por exemplo) ou para quem, pelo contrário, se encontra num ambiente ruidoso que as impeça de ouvir com clareza e, naturalmente, para quem não conheça o idioma em que se apresentam as legendas.</p>';
$manual[15] = '<p>Nem todos os agentes de utilizador, incluindo as ajudas técnicas, são capazes de interpretar os textos alternativos definidos para cada área activa dos mapas de tipo cliente. Isto faz supor que são muitos os utilizadores que não têm acesso a essa informação, pelo que é imprescindível incluir uma lista de <span lang="en" xml:lang="en">links</span>, constituida por texto, que apontem para os mesmos documentos que as áreas do mapa.</p>';
$manual[21] = '<p>Se se transmite informação importante ou funcional apenas através da cor, os utilizadores que não possam percepcionar a cor não poderão acompanhar a funcionalidade ou receber a mensagem de forma apropriada.</p>
<p>Para além dos utilizadores cegos e aqueles com deficiências na percepção da cor, devendo aqui incluir-se também as pessoas que acedem através de dispositivos com ecrãs monocromáticos ou que, por circunstâncias ambientais, se vêem impedidas de percepcionar a informação diferenciada unicamente na cor.</p>';
$manual[22] = '<p>Cerca de 10 por cento da população masculina mundial é daltónica, ou seja, têm uma deficiência de percepção das cores vermelha, verde ou azul.</p>
<p>Para além disso, há pessoas com cegueira total à cor e pessoas que utilizam dispositivos de saída monocromática, que requerem o uso de um alto contraste entre o fundo e a frente dos conteúdos no ecrã para poderem ser diferenciados correctamente.</p>
';
$manual[31] = '<p>As linguagens hipertexto usadas para criar as páginas Web permitem que o conteúdo definido com elas seja igualmente interpretado por um ser humano ou por uma ajuda técnica.</p>
<p>No caso das imagens, os agentes de utilizador não conseguem interpretar/descrever o conteúdo das imagens. Por isso é conveniente usar uma linguagem hipertexto, sempre que exista uma cujo resultado se revele apropriado para o efeito, ou seja, que possa transmitir a informação.</p>';
$manual[32] = '<p>A correcção na sintaxe do código fonte das páginas Web é importante para a sua adequada descodificação por parte dos agentes de utilizador, nos quais se incluem as ajudas técnicas.</p>
<p>Todas as páginas devem conter uma declaração do tipo de documento (DTD) para indicar formalmente aos agentes de utilizador qual é a linguagem hipertexto utilizada e desta forma ser possível verificar a correcção da sua gramática.</p>';
$manual[33] = '<p>As folhas de estilo representam um grande passo em frente para a Web. Com a separação de conteúdo e apresentação entre HTML e folhas de estilo é possível almejar o ideal de ter uma Web independente de plataformas ou dispositivos.</p>
<p>Com as <acronym title="Cascading Style Sheets" xml:lang="en" lang="en">CSS</acronym> é possível modificar a apresentação dos documentos sem recorrer a elementos e atributos obsoletos do HTML. Também tornam desnecessárias estratégias anticuadas que levavam a uma utilização incorrecta dos elementos do código apenas para  conseguir determinados efeitos visuais.</p>
';
$manual[34] = '<p>Se se utilizam unidades de medida relativas, os utilizadores poderão ampliar ou reduzir o tamanho dos elementos da página de acordo com as suas necessidades. Estas necessidades varíam de utilizador para utilizador em função das suas deficiências ou dos dispositivos que utilizam para aceder à Web.</p>';
$manual[35] = '<p>Alguns agentes de utilizador utilizam os cabeçalhos para extrair a estrutura do documento e disponibilizar melhores ferramentas de consulta, por exemplo, a possibilidade de examinar rapidamente as páginas navegando através dos títulos ou cabeçalhos. Mas, para além dos utilizadores poderem navegar de cabeçalho em cabeçalho, também alguns robots de pesquisa e indexação os utilizam para classificar as páginas, pelo que é muito importante marcar apropriadamente os cabeçalhos.</p>
<p>Cada secção de um documento deve apresentar-se com o cabeçalho HTML correspondente (H1-H6) segundo o nível que ocupe dentro da sua estrutura. Por exemplo, os cabeçalhos H2 devem aparecer depois dos elementos H1, os cabeçalhos H3 devem aparecer a seguir aos H2, etcétera.</p>
<p>Não se deve mesclar os níveis dos cabeçalhos de forma aleatória apenas para aproveitar os distintos tamanhos de fonte associados aos elementos <H>. Para melhorar a apresentação ou criar efeitos visuais no texto, utilize folhas de estilo em cascata e ordene os cabeçalhos apropriadamente.</p>
</ul>';
$manual[36] = '<p>Todo o conteúdo que configure uma lista de elementos deve estar marcado como lista. As marcas de lista são mais um elemento que permite marcar a estrutura de um documento. Não deve ser utilizado o código de lista para conseguir efeitos de apresentação. Os agentes de utilizador, nos quais se incluem as ajudas técnicas, diferenciam os elementos que configuram uma lista e que se encontram codificados como tal, facilitando a sua compreensão aos utilizadores.</p>
<p>HERA destaca as listas (DL, OL, UL) e respectivos itens. Certifique-se que se encontram correctamente marcados. Verifique se as listas se encontram correctamente entrelaçadas e o seu uso é apropriado.</p>';
$manual[37] = '<p>Uma vez que em cada idioma se utilizam diferentes estilos de aspas para identificar e delimitar uma citação, o elemento <Q> em HTML permite que os navegadores com suporte internacional mostrem as aspas em conformidade sem necessidade de inseri-las mediante o código ASCII. Este elemento usa-se para marcar citações curtas, uma frase, uma expressão.</p>
<p>O elemento <BLOCKQUOTE> identifica um bloco de texto citado e o elemento <CITE> uma citação ou referência para outros recursos.</p>
<p>Os agentes de utilizador, nos quais se incluem as ajudas técnicas, tratam a apresentação dos conteúdos marcados com estes elementos de uma maneira especial, indentando-os ou dando-lhes um destaque distinto, como seja verbalizar os mesmos com entoação diferente quando lidos por um leitor de ecrã que faça uso de sintetizador de fala. Não deve utilizar-se estes códigos simplemente para conseguir efeitos especiais, já que são marcas com significado estrutural que são utilizadas por robots de pesquisa e indexação para classificar esses conteúdos.</p>';
$manual[41] = '<p>Todos os conteúdos apresentados num idioma distinto ao declarado como principal da página, devem ser marcados, indicando-se o idioma em que estão escritos. Para além disso, os <span lang="en" xml:lang="en">links</span> que apontem para recursos em idiomas distintos ao principal da página, devem ser marcados com o atributo "hreflang" para indicar o idioma em que se apresentarão os conteúdos desse recurso. Isto é especialmente importante para quem utiliza leitores de ecrã capazes de pronunciar apropriadamente os conteúdos no idioma definido, para quem utiliza linhas braille para seleccionar a respectiva grafia braille e, quem desconheça o idioma em questão poderão recorrer a dispositivos apropriados para os traduzir. Para além disso, os robots de pesquisa e indexação podem assim classificar melhor esses conteúdos, facilitando todos os utilizadores na sua consulta.</p>
<p>HERA destaca as marcas de alteração de idioma e as indicações do idioma nos <span lang="en" xml:lang="en">links</span>. Verifique que todos as alterações de idioma, se encontram correctamente identificadas.</p>
<p>Se a página contém um elemento multimédia, verifique se se identifica a alteração na linguagem utilizada nas legendas, quando estas existam. Para isso, há que rever o código fonte das legendas, o que pode ser feito com <a href="http://www.hisoftware.com/" lang="en" hreflang="en">HiCaption</a> ou lendo o conteúdo do arquivo <acronym title="Synchronized Multimedia Integration Language" lang="en">SMIL</acronym> em qualquer editor de textos.</p>';
$manual[42] = '<p>Há que ter em conta que nem todos os utilizadores de um sítio têm que estar a par e familiarizados com o significado de todas as abreviaturas e acrónimos utilizados nas suas páginas. Por isso é importante explicitar o seu significado a primeira vez que aparecem e marcá-los sempre, utilizando o atributo "title" para definir a sua expansão. Desta maneira os agentes de utilizador serão capazes de indicar ao utilzador o seu significado.</p>
<p>Se tem dúvidas sobre a diferença entre uma abreviatura e um acrónimo, leia: "<a href="http://www.sidar.org/funacti/inves/abrvsacr.php" title="Explica como diferenciar uma abreviatura de um acrónimo.">Abreviaturas <abbr title="versus">vs.</abbr> Acrónimos</a>".</p>
<p>Há ainda que verificar que a <strong>expansão</strong> das abreviaturas (ABBR) e dos acrónimos (ACRONYM) está especificada quando aparece pela <strong>primeira vez no documento</strong> e que <strong>todas</strong> as abreviaturas e acrónimos se encontram <strong>marcadas</strong>.</p>';
$manual[43] = '<p>Em todas as páginas deve indicar-se o idioma principal utilizado. Desta maneira os agentes de utilizador poderão apresentar os conteúdos de acordo com o idioma marcado. Isto é especialmente importante para quem usa leitores de ecrã ou navegadores com síntese de fala e/ou linha braille, pois caso contrário não poderão ouvir/receber os conteúdos com a pronúncia/grafia correcta. Também é importante marcar o idioma principal do documento para que a página possa ser indexada apropriadamente.</p>
<p>Isto faz-se, por exemplo numa página criada em <acronym title="HyperText Markup Language" lang="en">HTML</acronym> no elemento que marca o início da página, i.e. "html".</p>';
$manual[51] = '<p>Para que os agentes de utilizador, nos quais se incluem as ajudas técnicas, possam interpretar correctamente os dados apresentados na forma tabular, as tabelas devem estar correctamente marcadas.</p>
<p>As células de cabeçalhos devem estar marcadas como &lt;TH&gt; e as células de dados, como &lt;TD&gt;.</p>';
$manual[52] = '<p>Se na página existir uma tabela de dados com dois ou mais níveis lógicos de cabeçalhos de linha ou coluna, deve associa-rse o conteúdo das células de dados com a sua correspondente célula de cabeçalho. Desta maneira, os agentes de utilizador que utilizam síntese de fala, poderão transmitir a relação entre os distintos elementos da tabela.</p>';
$manual[53] = '<p>Por principio não se devem utilizar tabelas para maquetar ou dispor o conteúdo de uma página. No caso de serem utilizadas para esse fim, deve verificar se a leitura da tabela linha a linha é compreensível. Caso contrário deve oferecer uma página alternativa com o conteúdo da tabela apresentada de forma linear.</p>
<p>As tabelas, como o seu próprio nome indica, existem para apresentar conteúdo tabular. Se o conteúdo não é tabular não deve apresentar-se dentro de uma tabela. Isto é especialmente importante para quem utiliza navegadores só de texto e quem utiliza leitores de ecrã antigos que efectuam, como estratégia comum, a leitura linha a linha do que aparece no monitor, juntando o conteúdo das células das colunas apresentadas na mesma linha, o que resulta em algo totalmente incompreensível.</p>';
$manual[54] = '<p>Quando numa tabela se marca um cabeçalho, todos os navegadores destacam visualmente o seu conteúdo. Por isso alguns autores, que usam tabelas para maquetar o conteúdo, marcam alguns elementos como cabeçalhos de tabela com o único propósito de que o navegador os destaque. Este ponto de controlo solicita explícitamente que não se faça isto. Portanto, há que verificar se as células de cabeçalho das tabelas (&lt;TH&gt;) não sejam usadas incorrectamente para dar formato à página.</p>
';
$manual[55] = '<p>As tabelas de dados devem levar um sumário ou resumo, marcado com o atributo <summary>. Isto facilitará a compreensão do conteúdo, da relação entre os elementos da tabela, aos utilizadores cujas aplicações suportam este atributo.</p>';
$manual[56] = '<p>As células que usam marcas para associar dados com cabeçalhos cujas etiquetas são muito grandes, devem estas ter a sua correspondente abreviatura, para que, quem usa leitores de ecrã, lhes seja mais fácil comprender a relação entre os dados, sem necessidade de ouvir constantemente descrições extensas da relação de um dado com um cabeçalho.</p>';
$manual[61] = '<p>É possível que um utilizador utilize um navegador que não suporte a definição de estilos mediante folhas de estilo em cascata. Também é possível que o utilizador utilize a sua propria folha de estilos. É por isso importante que os conteúdos da página possam  compreender-se mesmo sem a aplicação dos estilos definidos pelo autor.</p>';
$manual[62] = '<ul>
<li>Os painéis devem ser compostos por documentos com formatos capazes de conter textos alternativos e descrições (<acronym title="HyperText Markup Language" lang="en">HTML</acronym>, <acronym title="Extensible HyperText Markup Language" lang="en">XHTML</acronym>, etc.) e não, por exemplo, por uma imagem, uma vez que neste caso se limitaria o acesso ao seu conteúdo. Numa construção do tipo &#039;&lt;FRAME src="image.gif"&gt;&#039; os utilizadores com deficiência da visão ou mesmo aqueles que não dominam o idioma presente na página e que queiram recorrer a tradutores automáticos, não o vão conseguir fazer.</li>
<li>Quando numa página aparecem múltiplas imagens que se servem de forma aleatória, por exemplo, usando para o efeito scripts, o seu equivalente alternativo deve ser apropriado e deve também acompanhar essas alterações.</li>
</ul>
<p>Nem todos os utilizadores usam aplicações capazes de interpretar os scripts ou os painéis. Por essa razão é importante que exista um conteúdo alternativo, que se actualize à medida que o conteúdo é apresentado por essas tecnologías.</p>';
$manual[63] = '<p>Oss utilizadores podem preferir não descarregar ou executar objectos de programação, ou é possível que as suas aplicações não os suportem. Logo, os conteúdos das páginas e toda a sua interactividade e funcionalidade deve estar disponível sem a execução desses objectos.</p>
<p>Para rever este ponto, HERA destaca os elementos APPLET e OBJECT. Se na página há este tipo de elementos, desactive os plugins e verifique se é possível interactuar com a página.</p>
<p>Para isso, no Opera, pressione F12 ou no menú "File" opção "Quick Preferences", desactive as opções: "Enable Java", "Enable plug-ins" e "Enable Javascripts". Feito isto, verifique que todas as funções da página continuam a ser activáveis. E se não for esse o caso, se existe um <span lang="en" xml:lang="en">link</span> para uma versão alternativa a essa página com o mesmo conteúdo mas acessível.</p>';
$manual[64] = '<p>Os eventos devem poder activar-se de igual forma quer com o rato quer com o teclado. Porque existem utilizadores que não podem ou não querem utilizar o rato ou o teclado, devem existir manipuladores de evento independentes do tipo de dispositivo ("onfocus", "onblur", "onselect") ou redundantes para o tipo de dispositivo (se se indica "Onmousedown" deve indicar-se também "Onkeydown", se "onmouseup" também "onkeyup", se "onclick" também "onkeypress".).</p>';
$manual[65] = '<p>Os conteúdos dinâmicos devem ser directamente acessíveis para todos os agentes de utilizador, nas quais se incluem as ajudas técnicas, ou oferecer uma apresentação ou página alternativa. Logo, há que rever a existência deste tipo de conteúdos.</p>';
$manual[71] = '<p>Se o ecrã cintila, pode causar problemas, inclusivamente com graves consequências, como um ataque epiléptico, a alguns utilizadores. Portanto, deve evitar esse efeito.</p>';
$manual[72] = '<p>Comprove visualmente se se produzem flashes num conteúdo da página, o que pode ocasionar problemas a alguns utilizadores.</p>';
$manual[73] = '<p>Se se produzem movimentos na página, aos utilizadores com problemas de atenção, por exemplo, ser-lhes-á difícil interagir com o sítio, pelo que, esses movimentos devem ser evitados ou o utilizador deverá ser capaz de os interromper.</p>';
$manual[74] = '<p>Se uma página se auto reinicia automaticamente, muitos utilizadores não poderão, nunca, chegar a receber o seu conteúdo completo, porque cada vez que se reinicia a página as suas ajudas técnicas reiniciam também a leitura desde o principio de novo. Portanto, não deve provocar o reiniciar automático.</p>';
$manual[75] = '<p>Se existe um redireccionamento automático, o utilizador pode desorientar-se, e por outro lado essa função, interrompe o ciclo histórico de páginas visitadas que é guardado pelo agentes do utilizador.</p>';
$manual[81] = '<p>Este ponto compreende dois níveis de prioridade: Considera-se de nivel 1 se a funcionalidade é importante e de nivel 2 se não o é:</p>
<ul>
<li>Um exemplo de funcionalidade importante é o envío de um formulário ou o cálculo de uma quantidade, por exemplo, a soma total de um pedido, ou a ilustração de uma experiência de física na qual o objecto permite manipular algo virtualmente e não pode ser replicado de maneira alternativa.</li>
<li>Um exemplo de funcionalidade pouco importante sería um efeito decorativo como o realçar de uma imagem ou a alteração de cor de um texto.</li>
</ul>';
$manual[91] = '<p>É sempre preferível que os mapas de imagem sejam do tipo cliente, a não ser que as suas áreas não possam ser definidas por uma figura geométrica.</p>';
$manual[92] = '<p>Os vídeos incrustados, as animações flash, etc. devem poder manipular-se tanto com o rato tanto com o teclado. Em síntese, qualquer elemento que tenha a sua própria interface deve poder manipular-se tanto com o rato tanto com o teclado, uma vez que existem utilizadores que não podem usar um ou outro.</p>';
$manual[93] = '<p>Os eventos devem poder activar-se de igual forma com o rato ou con o teclado (porque há utilizadores que não podem usar um ou outro). Portanto deve haver manipuladores de evento independentes do tipo de dispositivo ("onfocus", "onblur", "onselect") ou redundantes para o tipo de dispositivo (se se indica "Onmousedown" deve indicar-se também "Onkeydown", se "onmouseup" também "onkeyup", se "onclick" também "onkeypress").</p>';
$manual[94] = '<p>Para os utilizadores que utilizam o teclado para navegar pelas páginas, é muito importante que a ordem de apresentação dos elementos siga uma ordem lógica de leitura.</p>
<p>A comprovação pode fazer-se visualmente na visão original da página (pressionando o botão que tem HERA para tal efeito), usando as teclas "a" e "q". A navegação por entre os <span lang="en" xml:lang="en">links</span> da página, controlos de formulário e objectos, deve seguir uma ordem lógica.</p>';
$manual[95] = '<p>Os atalhos de teclado facilitam quem utiliza o teclado para navegar, aceder de forma mais rápida aos elementos mais importantes da página, evitando ainda ter que passar por cada um antes de chegar ao que realmente lhes interessa e, no caso de quem utiliza leitores de ecrã (pessoas cegas, pessoas com deficiência visual, pessoas com dislexia, pessoas com problemas de atenção, etc.), ter de ouvir todos os elementos que existem antes de chegar ao que querem activar.</p>';
$manual[101] = '<p>Algo que é especialmente importante para os utilizadores que usam ajudas técnicas, é que o foco se mantenha na janela que contenha o documento que estão a visitar. Por isso, deve avisar-se, sempre, antes que alguma janela ou mensagem emergente capture o foco. Significa isto que, não se deve abrir janelas, nem efectuar chamadas emergentes, sem avisar antes o utilizador.</p>';
$manual[102] = '<p>Para facilitar a compreensão e o acesso aos controlos de formulário, estes devem levar associados etiquetas, de forma a que os agentes de utilizador possam interpretar adequadamente a sua relação.</p>
<p>A propriedade FOR de &lt;<span lang="en" xml:lang="en">label</span>&gt; deve coincidir com o ID do controlo de formulário.<br />
As etiquetas devem aparecer à esquerda ou na linha imediatamente anterior aos campos de edição e à direita ou na linha imediatamente posterior às casas de verificação ou quadros de selecção</p>';
$manual[103] = '<p>Ainda existem agentes de utilizador que lêem o conteúdo da página linha a linha, de forma que, se o conteúdo se apresenta em duas ou mais colunas, as aplicações misturam o que aparece em cada uma delas na mesma linha. Por esta razão, se na página existe conteúdo que ocupa mais do que uma linha em cada célula de uma tabela, deve oferecer-se uma versão linear desse conteúdo na mesma página ou noutra.</p>';
$manual[104] = '<p>Ainda hoje há ajudas técnicas que não são capazes de detectar o ponto exacto no qual se deve colocar o cursor nos controlos de formulário que se encontram vazios. Por esta razão, solicita-se que os campos de edição e as áreas de texto contenham algum carácter. Também é útil para os utilizadores com determinados tipos de deficiências cognitivas, o que nesses campos e áreas de texto há uma explicação do tipo de texto que eles devem introduzir. Por outro lado, isto leva a confusões a alguns utilizadores inexperientes que não sabem que devem substituir o texto existente pelo que eles introduzirem, pelo que se as etiquetas são suficientemente explícitas, bastará que exista texto por omissão no primeiro campo de um formulário.</p>';
$manual[105] = '<p>Alguns agentes de utilizador, nos quais se incluem as ajudas técnicas, não são capazes de diferenciar os <span lang="en" xml:lang="en">links</span> se se encontram um junto a outro sem nenhum elemento de programação hipertexto ou carácter imprimível que os separe.</p>';
$manual[111] = '<ul>
<li>As tecnologías do <acronym>W3C</acronym> disponíveis e suportadas são:
<ul>
	<li><acronym title="Mathematical Markup Language" lang)"en">MathML</span> para equações matemáticas</li> 
	<li><acronym title="HyperText Markup Language" lang="en">HTML</acronym>, <acronym title=" Extensible HyperText Markup Language" lang="en">XHTML</acronym>, <acronym title="Extensible Markup Language" lang="en">XML</acronym> para documentos estruturados</li>
	<li><acronym title="Resource Description Framework" lang="en">RDF</acronym> para meta dados</li>
	<li><acronym title="Synchronized Multimedia Integration Language" lang="en">SMIL</acronym> para criar apresentações multimédia</li>
	<li><acronym title="Cascading Style Sheet" lang="en">CSS</acronym> e <acronym title="Extensible Stylesheet Language" lang="en">XSL</acronym> para definir folhas de estilo</li>
	<li><acronym title="Extensible Stylesheet Language Transformations" lang="en">XSLT</acronym> para criar transformações de estilo</li>
	<li><acronym title="Portable Network Graphics" lang="en">PNG</acronym> para gráficos (apesar de alguns tipos se apresentarem melhor em JPG, que é uma especificação que não é do <acronym>W3C</acronym>)</li> 
</ul>
</li>
</ul>';
$manual[112] = '<p>Dependendo da linguagem utilizada para construir a página, é possível que se esteja a fazer uso de elementos obsoletos ou desaconselháveis, que podem resultar numa barreira de acesso a alguns utilizadores (por exemplo, o elemento &lt;FONT&gt; que defina determinadas características fixas para um texto, impedindo que o utilizador as possa modificarlo de acordo com as suas necessidades).</p><p>Lembre-se que o <acronym title="HyperText Markup Language" lang="en">HTML</acronym> admite mais elementos que o <acronym title="Extensible HyperText Markup Language" lang="en">XHTML</acronym> e que as versões <span lang="en">Strict</span> são mais restritivas que a <span lang="en">Transitional</span>, por exemplo.</p>';
$manual[113] = '<p>Que os utilizadores podem receber os documentos segundo as suas preferências, significa, por exemplo: num determinado idioma, num determinado tipo de conteúdo, num determinado formato, etc.</p>
<ul>
<li>Os utilizadores podem preferir receber os conteúdos no seu próprio idioma, escutar as páginas em vez de as ver, ter à sua disposição distintas formas de apresentação do conteúdo ou receber o conteúdo de forma apropriada por diversos meios como <span lang="fr">Braille</span> ou telefone de texto (<abbr title="TeleTYpe" lang="en">TTY</abbr>).</li>
<li>Para rever isto, ver se se oferece o conteúdo em vários idiomas, mediante um <span lang="en" xml:lang="en">link</span> ou mediante negociação de conteúdo, para rever este  último elemento, altere o idioma de preferência no navegador e volte a entrar na página, se o conteúdo aparece no idioma eleito (por exemplo, português) é porque se está a oferecer a versão idiomática mediante a negociação de conteúdo.</li>
<li>Se se disponibilizam vídeos ou apresentações multimédia incrustadas, rever se oferecem legendas em vários idiomas.</li>
<li>Quando se der a possibilidade de descarregar um documento num determinado formato, devem disponibilizar-se outros formatos alternativos, como por exemplo: <acronym title="HyperText Markup Language" lang="en">HTML</acronym>, <abbr title="Word document format" lang="en">doc</abbr>, <acronym title="Rich Text Format" lang="en">rtf</acronym>, <acronym title="Portable Document Format" lang="en">pdf</acronym>, <abbr title="Unicode Text File" lang="en">txt</abbr>, etc. Comprovar se isto se faz assim e preferencialmente em formatos não proprietários.</li>
<li>Se possível, deve-se colocar no sítio um número de telefone gratuito, disponível 24 horas por dia, através do qual seja possível solicitar a informação.</li>
</ul>';
$manual[114] = '<p>Se a página não cumpre pelo menos com os pontos de prioridade 2 (nivel mínimo de acessibilidade requerido em toda a Europa e na maior parte dos países do mundo), verifique se existe um link para outra página que tenha o mesmo conteúdo e funcionalidade, mas em que se usem as tecnologías do <acronym title="World Wide Web Consortium" lang="en">W3C</acronym>, seja accesible e que se actualize tão frequentemente como esta que está a rever.</p>
<p>Nota: O ponto solicita que se crie outra página que seja acessível. NÃO pede, nem pode interpretar-se como solução que a outra página seja uma "versão texto".</p>';
$manual[121] = '<p>Os painéis podem causar graves problemas, especialmente aos utilizadores de algumas ajudas técnicas, e em qualquer caso é-lhes difícil de manipular. Por essa razão, se se utilizam painéis, é essencial que cada painel tenha um título, o mais descritivo possível do conteúdo que apresentam.</p>';
$manual[122] = '<p>É muito possível que mesmo incluindo um título em cada painel, não seja óbvio para o utilizador qual é o seu conteúdo e relação com os outros painéis. Por esta razão solicita-se que se descreva esta relação numa página à parte. O URL dessa página deve ser indicada com o atributo "longdesc" e, também, deve colocar-se um <span xml:lang="en" lang="en">link</span> para essa página no conteúdo do elemento &lt;NOFRAME&gt;.</p>';
$manual[123] = '<p>Os blocos de informação demasiado grandes dificultam a sua compreensão, especialmente a algumas pessoas com deficiências cognitivas. Por esta razão e por simples lógica, é conveniente estruturar os documentos criando blocos de informação adequados à mesma.</p>';
$manual[124] = '<p>O atributo FOR de cada etiqueta <LABEL> deve coincidir com o atributo ID do controlo de formulário. A isto é o que se chama de associação explícita. Isto é especialmente útil para quem usa alguns leitores de ecrã que desta maneira relacionam a etiqueta com o controlo de formulário e podem guiar o utilizador na sua interaccão.</p>';
$manual[131] = '<p>Um link deve indicar da forma mais clara e sucinta possível para onde aponta, o que encontrará o utilizador se seguir esse link. Isto é especialmente importante para os utilizadores de ajudas técnicas como os leitores de ecrã, e para as pessoas com dislexia e/ou dificuldades de aprendizagem.</p>';
$manual[132] = '<p>Os metadados são informação sobre os conteúdos da página e sobre outras questões relativas a ela e ao sítio em que se encontra, como dados do autor, data de caducidade se a tem, data de criação, etc. Facilitam a localização, do documento e dos seus conteúdos, na Web.</p>
<p>Alguns metadados proporcionam informação de orientação importante para o utilizador, outros podem proporcionar informação aos robots de pesquisa e indexação, outros proporcionam informação aos agentes de utilizador sobre a temática da página (por exemplo, se é apropriada ou não para crianças), os direitos de autor, etc. A declaração dos metadados pode ser feita mediante o elemento "meta" quando se referem a dados contidos no próprio documento, mediante o elemento "link" quando se referem a dados contidos num documento externo, ou se refira a um "profile"/perfil onde se define a propriedade e os seus atributos legais, mediante o atributo "profile".</p>
<p>São contentores de metadados, o elemento "title", o elemento "address", o elemento "meta", a declaração de tipo de documento (DTD), o elemento "link" e os elementos "del" e "ins", assim como os atributos "hreflang", "lang", "title" e "cite".</p><p>Se a página forma parte duma série, de uma colecção de documentos, por exemplo se forma parte junto com outras do que podería ser um manual, um catálogo, etc.; deve utilizar-se o elemento LINK para as relacionar.</p>';
$manual[133] = '<p>Um mapa ou índice dos conteúdos do sítio facilita a localização dos conteúdos e a comprender a relação entre as distintas páginas que compreendem um sítio.</p>
<p>Para verificar este ponto, há que ver se o sítio oferece um índice de conteúdos ou mapa do sítio, geralmente indicado com um link chamado "mapa". Se o sítio é muito pequeno, o próprio menú de navegação funcionará como índice de conteúdos.</p>';
$manual[134] = '<p>Os mecanismos de navegação, os links, icones, os menús, que podem ser de definição, de situação ou contextuais, são essenciais para a compreensão da estruturação e navegação pelas páginas, o sítio, e a situação do utilizador em cada momento da sua visita. Por isso é  muito importante, para todos os utilizadores, mas especialmente para quem tem  limitações para a leitura e aprendizagem, que se usem, de maneira consistente em todo o sítio, os mesmos mecanismos de navegação, estturura e estilo.</p>
<p>Para verificar a aplicação deste ponto, há que observar se os mecanismos de navegação, aparecem sempre na mesma localização. No caso em que se usem icones, se estes apontam sempre para o mesmo recurso e, se o comportamento desses mecanismos é sempre o mesmo.</p>';
$manual[135] = '<p>Se os elementos de navegação principais se disponibilizam de forma agrupada, numa "barra de navegação", destacam-se e facilita-se a sua localização. Para os utilizadores, especialmente para quem usa leitores de ecrã, isto é essencial pois desta maneira podem evitá-los em vez de ter que ouvir repetidamente um monte de elemento que já conhecem de outras passagens e não desejam escutar constantemente.</p>
<p>Para rever este ponto, há que ver se os elementos principais para a navegação pelo sítio se apresentam como uma barra de navegação (agrupados), que pode ser composta por icones, por textos ou por ambos.</p>';
$manual[136] = '<p>Se se agrupam os links relacionados, será mais fácil reconhecê-los como um barra de navegação, o que facilitará a sua localização em qualquer página do sítio. Isto é especialmente importante para os utilizadores que não podem ver e para os que têm dificuldades de aprendizagem.</p>
<ul>
<li>Uma vez que uma série de links para as secções principais do sítio são constituídos por uma lista, devem marcar-se como lista.</li>
<li>O ideal é que os botões ou links que constituem a barra de menú formem parte de um elemento <map> que leve um título que identifique que o seu conteúdo é uma barra de navegação. Isto facilitará quem usa agentes de utilizador que seguem a especificação, permitindo saltar esse grupo de elementos.</li>
<li>Ver se os links estão relacionados entre sí, marcados como listas, e preferencialmente como parte de um elemento <map></li>
<li>Como ainda nem todos os agentes de utilizador são capazes de saltar, quando o utilizador o solicita, os agrupamentos de elementos, deve-se disponibilizar um link que cumpra esta função. O link não deve ser composto por uma imagem invisível, deve ser um texto e deve, pelo menos, aparecer quando recebe o foco. Isto porque esse link será usado não apenas pelas pessoas cegas mas também por todos os utilizadores de leitores de ecrã e por por quem utiliza o teclado, teclado físico ou virtual, assim como software de varrimento, para navegar.</li>
</ul>';
$manual[137] = '<p>Se no sítio se oferece um sistema de pesquisa, é importante oferecer mecanismos de pesquisa que se acomodem a vários níveis de habilidade e preferência. A maioría dos utilitários de pesquisa requerem que o utilizador indique palavras chave para procurar térmos, pelo que os utilizadores com dificuldades para apagar, e aqueles para os quais não é familiar o idioma empregue no sítio, terão dificuldades no momento de encontrar o que necessitam, se o motor de busca exigir uma ortografía perfeita. Os processadores de pesquisa devem incluir um revisor ortográfico, oferecer a "melhor presunção" como alternativa, exemplos de pesquisas, pesquisas por similitude, etc.
</p>
<p>Para rever este ponto, se o sítio oferece um motor de busca, há que usá-lo para ver se oferece opções avançadas de pesquisa.</p>';
$manual[138] = '<p>Os utilizadores de leitores de ecrã (pessoas cegas, com baixa visão graves ou com algumas deficiências cognitivas e até mesmo pessoas com dislexia) desejam "folhear" as páginas, isto é, saltam de cabeçalho em cabeçalho e de parágrafo em parágrafo escutando apenas umas poucas palavras do parágrafo para determinar se realmente lhes interessa ouvi-lo completamente. Isso é algo que, na realidade, todos os utilizadores fazem, mesmo que não utilizemos leitores de ecrã, quando pesquisamos uma determinada informação e desejamos encontrá-la o mais rapidamente possível.</p>
<p>Se a idea principal ou assunto de cada parágrafo aparece no inicio, facilitar-se-á a compreensão do parágrafo e a navegação rápida, folhear, pela página.</p>';
$manual[139] = '<p>Se uma série de páginas constituem um documento, ao enlaçarem-se entre sí, da maneira que se explicará mais adiante, facilitará a sua leitura sem conexão à Internet e a navegação dentro dele, a todos os utilizadores e especialmente a quem utiliza o teclado para navegar.</p>
<p>Se os documentos (as páginas) estão relacionados entre sí, por exemplo se constituem uma apresentação, manual, folheto, etc.; para além dos metatags para os relacionar deve existir um "contador" que indique onde se encontra o utilizador, por exemplo: "Página 3 de 25" e botões ou links para as páginas anterior, seguinte e tabela de conteúdos ou índice.</p>';
$manual[1310] = '<p>Para quem usa leitores de ecrã, sería muito cansativo ter que ouvir uma serie de caracteres sem sentido, quando o leitor se encontra com um desenho criado por caracteres <abbr title="American Standard Code for Information Interchange" lang="en">ASCII</abbr>. Por esta razão é importante oferecer um modo que permita saltar o desenho e continuar com a leitura da página.</p>';
$manual[141] = '<p>Um sítio Web pode ser visitado e pode contar entre os "seus clientes" com pessoas com defeciências cognitivas, pessoas com baixo grau de alfabetização, pessoas que não dominam o idioma, etc.; em síntese com pessoas com limitações para a leitura.</p>
<ul>
<li>Nos sítios dirigidos a um público amplo, os conteúdos devem estar expressos numa linguagem clara e fácil, evitando anglicismos, linguagem corporativa, etc. Segundo as seguintes directrizes incrementar-se-á a facilidade de leitura e compreensão:
<ol>
<li>Cuidar para que os títulos e o texto dos links seja o mais claro e exactos possível. As palavras mais importantes devem reflectir a idea e ser, entre aquelas que constituem sinónimos, as que resultam mais comuns.</li>
<li>Especificar o tema das orações ou parágrafos no principio dos mesmos.</li>
<li>Limitar cada parágrafo a uma idea principal.</li>
<li>Evitar a gíria idiomática, as expressões e vocabulário não familiar (modismos, jargão).</li>
<li>Se se empregar palavras familiares com significados especiais, proporcionar explicações das mesmas.</li>
<li>Evitar a voz passiva.</li>
<li>Evitar estruturas complexas nas orações.</li>
<li>Nos links usar frases concisas mas com suficiente significado para serem entendidos mesmo fora do contexto.</li>
<li>A ortografía deve ser correcta.</li>
</ol>
</li>
</ul>';
$manual[142] = '<p>Os icones, as ilustrações, os vídeos e as animações, não devem cumprir uma função meramente decorativa. A sua correcta utilização aumenta a compreensão e facilita o uso de un sítio Web, para todos os utilizadores, mas especialmente para quem tem dificuldades de aprendizagem ou, por exemplo, para as pessoas surdas de nascença.</p>
<p>Por exemplo, um gráfico a acompanhar a apresentação de dados estatísticos torna-os mais fáceis de compreender, para todos. Um icone que represente uma determinada secção do sítio, será mais fácil de recordar e muitas vezes de compreender que uma palavra que pode não ter muito sentido para alguem que não conhece bem o idioma no que está escrito o sítio ou para alguem com dificuldades de leitura ou de concentração.</p>
<p>Para rever este ponto, há que valorar se na página se faz um uso apropriado de icones e de sons que acompanhan as acções, a ilustração dos conteúdos com imagens, vídeos, animações e/ou sons.</p>';
$manual[143] = '<p>Um estilo de apresentação consistente em cada uma das páginas de um sítio, permite aos utilizadores localizar mais facilmente o conteúdo importante. Isto ajuda as pessoas com problemas de aprendizagem e leitura, mas também torna a navegação mais fácil para todos os utilizadores. A previsibilidade incrementará a probabilidade das pessoas encontrarem a informação no seu sítio e ajudá-los-á a evitar o que não desejam.</p>
<ul>
<li>Os mecanismos de navegação e a sua localização, maquetação, cores, localização dos blocos de texto devem manter-se uniformes entre páginas, o que permite ficar de imediato alerta quando se entra no sítio... e também quando o abandonamos.</li>
<li>Os mecanismos de navegação e pistas visuais ou textuais que se disponibilizam em todas as páginas permitem minimizar os esforços do utilizador para saber quando chegou ao final do conteúdo ou que informação adicional pode ainda encontrar.</li>
</ul>
<p>Para rever e avaliar a aplicação deste ponto há que comparar a página que se está a rever com outras do mesmo sítio.</p>';
?>
