<?php
$manual[11] = '<p>No todos los usuarios pueden percibir apropiadamente los contenidos no textuales, ya sea porque tienen alguna deficiencia o porque sus equipos o conexiones se lo limitan. Por esta razón, el punto pide que, para todo contenido que no sea texto, se ofrezca una alternativa en formato texto mediante el marcado o las técnicas existentes para ello.</p>
<p>Las técnicas para proporcionar un contenido alternativo varía según cada elemento. Puede requerir el uso de atributos específicos, como "alt" o "longdesc"; el uso de otros elementos (&lt;script&gt;/&lt;noscript&gt;, por ejemplo) o la inclusión de los textos alternativos dentro de la propia marca, como es el caso de &lt;applet&gt; o &lt;iframe&gt;.</p>';
$manual[12] = '<p>Un mapa de imagen define zonas activas en un elemento &lt;img&gt; o &lt;input&gt;, de modo que es posible asociar una acción a cada una de esas zonas (típicamente activar un enlace).</p>
<p>En los mapas de imagen del tipo servidor, cuando el usuario activa un enlace utilizando el ratón, las coordenadas del puntero del ratón sobre la pantalla se envían al servidor donde reside el archivo con la definición del mapa.</p>
<p>Como se requiere un dispositivo de entrada específico (un ratón), se debe proporcionar información redundante creando una lista en formato texto de todos los vínculos definidos en el mapa, de modo que puedan ser activados también a través del teclado.</p>';
$manual[13] = '<p>Las presentaciones de video o animación deben proporcionar una descripción sonora de, por ejemplo, el escenario, los gráficos que se presentan, las acciones, etcétera, para los usuarios que no pueden ver o con deficiencias visuales.</p>';
$manual[14] = '<p>Ofrecer un equivalente textual o una descripción separados de una presentación multimedia no aportan la misma experiencia a las personas sordas o con deficiencias auditivas, ni a las personas que desconocen el idioma original de la presentación.</p>
<p>Por esta razón se deben incluir equivalentes alternativos sincronizados con la presentación. Estos son útiles no sólo para las personas sordas o con deficiencias auditivas, sino también para quienes deben trabajar en un ambiente silencioso (una biblioteca, por ejemplo) o quienes, por el contrario, se encuentran en un ambiente ruidoso que les impide oír con claridad y, naturalmente, para quienes no conocen el idioma en que se presentan los subtítulos.</p>';
$manual[15] = '<p>No todas las aplicaciones de usuario, incluidas las ayudas técnicas, son capaces de interpretar los textos alternativos definidos para cada área activa de los mapas de tipo cliente. Esto supone que muchos usuarios no tendrán acceso a esa información, por lo que es imprescindible incluir un listado de enlaces, constituidos por texto, que apunten a los mismos documentos que las áreas del mapa.</p>';
$manual[21] = '<p>Si se transmite información importante o funcional solamente a través del color, los usuarios que no pueden percibir el color no podrán seguir la funcionalidad o recibir el mensaje apropiadamente.</p>
<p>Además de los usuarios ciegos y aquellos con deficiencias en la percepción del color, deben considerarse a las personas que acceden mediante dispositivos con pantallas monocromas o que, por circunstancias ambientales, se ven impedidas de percibir la información basada únicamente en el color.</p>';
$manual[22] = '<p>Cerca del 10 por ciento de la población masculina mundial es daltónica, es decir, tiene una deficiencia de percepción de los colores rojo, verde o azul.</p>
<p>Además, hay personas con ceguera total al color y personas que utilizan dispositivos de salida monocromas, que requieren un alto contraste entre fondo y frente de los contenidos en pantalla para poder diferenciarlos correctamente.</p>
';
$manual[31] = '<p>Los lenguajes de marcado utilizados para crear las páginas Web permiten que el contenido definido con ellos sea igualmente interpretado por un ser humano como por una ayuda técnica.</p>
<p>Por el contrario, las aplicaciones no pueden interpretar el contenido de las imágenes. Por esa razón es conveniente usar un lenguaje de marcas, siempre que exista uno que resulte apropiado, para transmitir la información.</p>';
$manual[32] = '<p>La corrección en la sintaxis del código fuente de las páginas Web es importante para su adecuada decodificación por parte de las aplicaciones de usuario, incluidas las ayudas técnicas.</p>
<p>Todas las páginas deben contener una declaración del tipo de documento (DTD) para indicar formalmente a las aplicaciones cuál es el lenguaje de marcas utilizado y así poder verificar la corrección de su gramática.</p>';
$manual[33] = '<p>Las hojas de estilo representan un gran paso adelante para la Web. Con la separación de contenido y presentación entre HTML y hojas de estilo es posible lograr el ideal de una Web independiente de plataformas y dispositivos.</p>
<p>Con <acronym title="Cascading Style Sheets" xml:lang="en" lang="en">CSS</acronym> es posible modificar la presentación de los documentos si recurrir a elementos y atributos obsoletos en HTML. También hacen innecesarias antiguas estrategias que llevaban a utilizar incorrectamente los elementos del código sólo por conseguir determinados efectos visuales.</p>
';
$manual[34] = '<p>Si se utilizan unidades de medida relativas, los usuarios podrán ampliar o reducir el tamaño de los elementos de la página de acuerdo con sus necesidades. Estas necesidades varían de un usuario a otro en función de sus deficiencias o de los dispositivos que utilizan para acceder a la Web.</p>';
$manual[35] = '<p>Algunas aplicaciones de usuario utilizan los encabezados para extractar la estructura del documento y ofrecer mejores herramientas de consulta, por ejemplo, la posibilidad de examinar rápidamente las páginas navegando a través de los títulos o encabezados. Pero además de los usuarios que pueden navegar de encabezado en encabezado, también algunos robots de búsqueda e indexación los utilizan para clasificar las páginas, de manera que es muy importante marcar apropiadamente los encabezados.</p>
<p>Cada sección de un documento debe presentarse con el encabezado HTML correspondiente (H1-H6) según el nivel que ocupe dentro de su estructura. Por ejemplo, los encabezados H2 deben seguir a los elementos H1, los encabezados H3 deben seguir a los H2, etcétera.</p>
<p>No mezcle los niveles de encabezados aleatoriamente sólo para aprovechar los distintos tamaños de fuente que los navegadores adjudican a los elementos <H>. Para mejorar la presentación o crear efectos visuales en el texto, utilice hojas de estilo en cascada y ordene los encabezados apropiadamente.</p>
</ul>';
$manual[36] = '<p>Todo contenido que conforme una lista de elementos debe estar marcado como tal lista. Las marcas de lista son un elemento más que permite marcar la estructura de un documento. No debe utilizarse el marcado de lista para conseguir efectos de presentación. Las aplicaciones de usuario, incluidas las ayudas técnicas, diferencian los elementos que conforman una lista, facilitando su comprensión a los usuarios.</p>
<p>HERA destaca las listas (DL, OL, UL) y sus ítems. Compruebe que se encuentran correctamente marcados. Revise que las listas estén anidadas y utlizadas correctamente.</p>';
$manual[37] = '<p>Debido a que en cada idioma varían los estilos de comillas que se usan para identificar las citas, el elemento <Q> en HTML permite que los navegadores con soporte internacional muestren las comillas correspondientes sin necesidad de insertarlas mediante el código ASCII. Este elemento se usa para marcar citas cortas, una frase, una expresión.</p>
<p>El elemento <BLOCKQUOTE> identifica un bloque de texto citado y el elemento <CITE> una citación o referencia a otros recursos.</p>
<p>Las aplicaciones de usurio, incluidas las ayudas técnicas, tratan la presentación de los contenidos marcados con estos elementos de una manera especial, sangrándolos o poniendo una entonación distinta cuando al presentación se hace mediante síntesis de voz. No debe utilizarse este marcado simplemente para conseguir dichos efectos, ya que son marcas estructurales que son utilizadas por robots de búsqueda e indexación para clasificar esos contenidos.</p>';
$manual[41] = '<p>Todos los contenidos presentados en un idioma distinto al declarado como principal de la página, deben marcarse indicando el idioma en el que están escritos. Además, los enlaces que apunten a recursos en idiomas distintos al principal de la página, deben marcarse con el atributo "hreflang" para indicar el idioma en el que se presentarán los contenidos de ese recurso. Esto es especialmente importante para quienes utilizan lectores de pantalla capaces de pronunciar apropiadamente los contenidos en el idioma definido, para quienes utilizan líneas braille para seleccionar los códigos de control apropiados para que el programa de traducción genere los caracteres correctos y, quienes desconocen el idioma en cuestión podrán recurrir a dispositivos apropiados para traducirlos. Además, los robots de búsqueda e indización pueden así clasificar mejor dichos contenidos, facilitando a todos los usuarios su recuperación.</p>
<p>HERA destaca las marcas de cambios de idioma y las indicaciones del idioma en los enlaces. Verifique que todos los cambios de idioma, se encuentran correctamente identificados.</p>
<p>Si la página contiene un elemento multimedia, revisar si se identifica el cambio en el lenguaje utilizado en los subtítulos, cuando lo haya. Para lo cual, hay que revisar el código fuente de los subtítulos, lo que puede hacerse con <a href="http://www.hisoftware.com/">HiCaption</a> o leyendo el contenido del archivo SMIL en cualquier editor de textos.</p>';
$manual[42] = '<p>Hay que tener en cuenta que no todos los usuarios de un sitio tienen por qué conocer el significado de todas las abreviaturas y acrónimos utilizados en sus páginas. Por ello es importante explicitar su significado la primera vez que aparecen y marcarlas siempre, utilizando el atributo "title" para definir su expansión. De esta manera las aplicaciones de usuario serán capaces de indicarle al usuario su significado.</p>
<p>Si tiene dudas sobre la diferencia entre una abreviatura y un acrónimo, lea: "<a href="http://www.sidar.org/funacti/inves/abrvsacr.php" title="Explica cómo diferenciar una abreviatura de un acrónimo.">Abreviaturas <abbr title="versus">vs.</abbr> Acrónimos</a>".</p>
<p>Además hay que comprobar que la expansión de las abreviaturas (ABBR) y los acrónimos (ACRONYM) está especificada en su forma expandida cuando aparece por primera vez en el documento y que todas las abreviaturas y acrónimos se marcan.</p>';
$manual[43] = '<p>En todas las páginas debe indicarse el idioma principalmente usado en ellas. De esta manera las aplicaciones de usuario podrán presentar los contenidos de acuerdo con el idioma marcado. Esto es especialmente importante para quienes usan lectores de pantalla o navegadores con síntesis de voz, pues de otra manera no podrán escuchar los contenidos con la pronunciación correcta. También es importante marcar el idioma principal del documento para que la página pueda se indexada apropiadamente.</p>
<p>Esto se hace, por ejemplo en una página creada en <acronym title="HyperText Markup Language" lang="en">HTML</acronym> en el elemento "html".</p>';
$manual[51] = '<p>Para que las aplicaciones de usuario, incluidas las ayudas técnicas, puedan interpretar correctamente los datos presentados en forma tabular, las tablas deben estar correctamente marcadas.</p>
<p>Las celdas de encabezados deben estar marcadas como &lt;TH&gt; y las celdas de datos, como &lt;TD&gt;.</p>';
$manual[52] = '<p>Si en la página hay una tabla de datos con dos o más niveles lógicos de encabezado de fila o columna, debe asociarse el contenido de las celdas de datos con su correspondiente celda de encabezado. De esta manera, las aplicaciones de usuario que utilizan síntesis de voz, podrán transmitir la relación entre los distintos elementos de la tabla.</p>';
$manual[53] = '<p>Por principio no deben utilizarse tablas para maquetar o disponer el contenido de una página. Y en caso de que se utilicen para ese fin, debe comprobarse que si la tabla se lee línea a línea sigue siendo comprensible su contenido. En caso contrario debe ofrecerse una página alternativa con el contenido de la tabla presentado en forma lineal.</p>
<p>Las tablas, como su nombre indica, existen para presentar contenido tabular. Si el contenido no es tabular no debe presentarse dentro de una tabla. Esto es especialmente importante para quienes utilizan navegadores sólo texto y quienes utilizan lectores de pantalla que leen línea a línea lo que aparece en el monitor, porque de esta manera se junta el contenido de las celdas presentes en la misma línea, dando como resultado algo totalmente incomprensible.</p>';
$manual[54] = '<p>Cuando en una tabla se marca un encabezado, todos los navegadores destacan visualmente su contenido. Por ello algunos autores, que usan tablas para maquetar el contenido, marcan algunos elementos como encabezados de tabla con el único propósito de que el navegador los destaque. Este punto de control pide explícitamente que no se haga esto. Por tanto, hay que verificar que las celdas de encabezado de las tablas (&lt;TH&gt;) no sean usadas incorrectamente para dar formato a la página.</p>
';
$manual[55] = '<p>Las tablas de datos deben llevar un sumario o resumen, marcado con el atributo <summary>. Esto facilitará la comprensión del contenido, de la relación entre los elemento de la tabla, a los usuarios cuyas aplicaciones soportan este atributo y les leen su contenido.</p>';
$manual[56] = '<p>Las celdas que usan marcas para asociar datos con encabezados cuyas etiquetas son muy largas, deben tener su correspondiente abreviatura, para que a quienes usan lectores de pantalla para ayudarse en la comprensión de la página, les sea más sencillo comprender la relación entre los datos, sin necesidad de oír constantemente descripciones extensas de la relación de un dato con un encabezado.</p>';
$manual[61] = '<p>Es posible que un usuario utilice un navegador que no soporte la definición de estilos mediante Hojas de estilo en cascada, también es posible que el usuario utilice su propia hoja de estilos. Por lo que es importante que los contenidos de la página puedan comprenderse aún sin la aplicación de los estilos definidos por el autor.</p>';
$manual[62] = '<ul>
<li>Los marcos deben estar conformados por documentos con formatos capaces de contener textos alternativos y descripciones (<acronym title="HyperText Markup Language" lang="en">HTML</acronym>, <acronym title="Extensible HyperText Markup Language" lang="en">XHTML</acronym>, etc.) y no por una imagen, por ejemplo, porque entonces se limitaría el acceso a su contenido a todos los usuarios con deficiencas visuales o, por ejemplo, a aquellos que no conocen bien el idioma y, por tanto, no podrían utilizar en ellos las aplicaciones de traducción automática.</li>
<li>Cuando en una página aparecen imágenes que se sirven de forma aleatoria, por ejemplo, mediante scripts, su equivalente alternativo debe ser apropiado a ese cambio.</li>
</ul>
<p>No todos los usuarios utilizan aplicaciones capaces de interpretar los scripts o los marcos. Por esa razón es importante que exista un contenido alternativo para ellos, que se actualice a la vez que el contenido presentado mediante esas tecnologías.</p>';
$manual[63] = '<p>Los usuarios pueden preferir no descargar o ejecutar objetos de programación, o es posible que sus aplicaciones no los soporten. Por tanto, los contenidos de las páginas y toda su interactividad y funcionalidad debe estar disponible sin la ejecución de esos objetos.</p>
<p>Para revisar este punto, HERA destaca los elementos APPLET y OBJECT. Si en la página hay este tipo de elementos, desactive los plugins y verifique si es posibile interactuar con la página.</p>
<p>Para ello, en Opera, pulsando F12 o en el menú "File" opción "Quick Preferences", deshabilitar las opciones: "Enable Java", "Enable plug-ins" y "Enable Javascripts". Una vez hecho esto, revisar que todas las funciones de la página siguen siendo activables. Y si no es así, si hay un enlace a una versión alternativa de esa página con el mismo contenido pero accesible.</p>';
$manual[64] = '<p>Los eventos deben poder activarse de igual forma con el ratón que con el teclado. Porque hay usuarios que no pueden o no quieren utilizar el ratón o el teclado. Por tanto debe haber manejadores de evento independientes del tipo de dispositivo ("onfocus", "onblur", "onselect") o redundantes para el tipo de dispositivo (si se indica "Onmousedown" debe indicarse también "Onkeydown", si "onmouseup" también "onkeyup", si "onclick" también "onkeypress".).</p>';
$manual[65] = '<p>Los contenidos dinámicos deben ser directamente accesibles para todas las aplicaciones de usuario, incluidas las ayudas técnicas, u ofrecerse en una presentación o página alternativa. Por tanto, hay que revisar la existencia de este tipo de contenidos.</p>';
$manual[71] = '<p>Si la pantalla parpadea, puede causar molestias e incluso graves consecuencias, como un ataque epiléptico, a algunos usuarios. Por tanto, debe evitarse ese efecto.</p>';
$manual[72] = '<p>Compruebe visualmente si se producen destellos en algún contenido de la página, lo que puede ocasionar molestias a algunos usuarios.</p>';
$manual[73] = '<p>Si se producen movimientos en la página, a los usuarios con problemas de atención, por ejemplo, les será difícil interactuar con el sitio, por tanto, esos movimientos deben evitarse o el usuario debe poder detenerlos.</p>';
$manual[74] = '<p>Si una página se autorefresca automáticamente, muchos usuarios no podrán llegar a recibir su contenido completo nunca, pues cada vez que se refresque la página sus ayudas técnicas comenzará a leerla o repasarla de nuevo. Por tanto, no debe provocarse el refresco automático.</p>';
$manual[75] = '<p>Si existe un redireccionamiento automático, el usuario puede desorientarse, además eso interrumpe el ciclo histórico de página visitadas que guarda la aplicación del usuario.</p>';
$manual[81] = '<p>Este punto comprende dos niveles de prioridad: Se considera de nivel 1 si la funcionalidad es importante y de nivel 2 si no lo es:</p>
<ul>
<li>Un ejemplo de funcionalidad importante es el envío de un formulario o el cálculo de una cantidad, por ejemplo, la suma total de un pedido, o la ilustración de un experimento de física en la que el objeto permite manipular algo virtualmente y no puede duplicarse de manera alternativa.</li>
<li>Un ejemplo de funcionalidad poco importante sería un efecto decorativo como el resaltado de una imagen o el cambio de color de un texto.</li>
</ul>';
$manual[91] = '<p>Siempre es preferible que los mapas de imagen sean de tipo cliente, a menos que sus áreas no puedan ser definidas con una figura geométrica.</p>';
$manual[92] = '<p>Los vídeos incrustados, las animaciones flash, etc. deben poder manejarse tanto con ratón como con teclado, en resumen, cualquier elemento que tenga su propia interfaz debe poder manejarse tanto con el ratón como con el teclado, pues hay usuarios que no pueden usar uno u otro.</p>';
$manual[93] = '<p>Los eventos deben poder activarse de igual forma con el ratón que con el teclado (porque hay usuarios que no pueden usar uno u otro). Por tanto debe haber manejadores de evento independientes del tipo de dispositivo ("onfocus", "onblur", "onselect") o redundantes para el tipo de dispositivo (si se indica "Onmousedown" debe indicarse también "Onkeydown", si "onmouseup" también "onkeyup", si "onclick" también "onkeypress").</p>';
$manual[94] = '<p>Para los usuarios que utilizan el teclado para navegar por las páginas, es muy importante que el orden de presentación de los elementos siga un orden lógico de lectura.</p>
<p>La comprobación puede hacerse visualmente en la vista original de la página (pulsando el botón que tiene HERA a tal efecto) y una vez en ella las teclas "a" y "q". La navegación por entre los enlaces de la página, controles de formulario y objetos, debe seguir un orden lógico.</p>';
$manual[95] = '<p>Los atajos de teclado facilitan a quienes utilizan el teclado para navegar, acceder de forma más rápida a los elementos más importantes de la página, evitándoles además el tener que pasar por cada uno antes de llegar al que realmente les interesa y, en el caso de quienes utilizan lectores de pantalla (personas ciegas, personas con deficiencia visual, personas con dislexia, personas con problemas de atención, etc.), el tener que oír todos los elementos que existen antes de donde se encuentra el que quieren activar.</p>';
$manual[101] = '<p>Especialmente importante para los usuarios que utilizan ayudas técnicas es que el foco se mantenga en la ventana que contiene el documento que están visitando. Por ello, debe avisarse siempre antes de que ninguna ventana o mensaje emergente capture el foco. Es decir, no deben abrirse ventanas, ni llamadas emergentes, sin avisar antes al usuario.</p>';
$manual[102] = '<p>Para facilitar la comprensión y el acceso a los controles de formulario, éstos deben llevar asociadas etiquetas, de manera que las aplicaciones de usuario puedan interpretar adecuadamente su relación.</p>
<p>La propiedad FOR de label debe coincidir con el ID del control de formulario.<br />
Las etiquetas deben aparecer a la izquierda o en la línea inmediatamente anterior a los campos de edición y a la derecha o en la línea inmediatamente posterior a las casillas de verificación o cuadros de selección</p>';
$manual[103] = '<p>Aún existen aplicaciones de usuario que leen el contenido de la página línea a línea, de manera que si el contenido se presenta en dos o más columnas la aplicación mezcla lo que aparece en cada una de ellas en la misma línea. Por esta razón, si en la página existe contenido que ocupa más de una línea en cada celda de una tabla, debe ofrecerse una versión lineal de ese contenido en la misma página o en otra.</p>';
$manual[104] = '<p>Aún hoy hay ayudas técnicas que no son capaces de detectar el punto exacto en el que debe colocarse el cursor en los controles de formulario que se encuentran vacíos. Por esta razón, se pide que los campos de edición y áreas de texto contengan algún caracter. También es útil para los usuarios con determinados tipos de deficiencias cognitivas, el que en esos campos y áreas de texto haya una explicación del tipo de texto que ellos deben introducir. Por otra parte, esto lleva a confusión a algunos usuarios inexpertos que no saben que deben reemplazar el texto existente por el que ellos introduzcan, por lo que si las etiquetas son suficientemente explícitas, bastará con que haya texto por omisión en el primer campo de un formulario.</p>';
$manual[105] = '<p>Algunas aplicaciones de usuario, incluidas algunas ayudas técnicas, no son capaces de diferenciar los enlaces si se encuentran uno junto a otro sin ningún marcado o caracter imprimible que los separe.</p>';
$manual[111] = '<ul>
<li>Las tecnologías del W3C disponibles y soportadas son:
<ul>
	<li>MathML para ecuaciones matemáticas</li> 
	<li><acronym title="HyperText Markup Language" lang="en">HTML</acronym>, XHTML, XML para documentos estructurados</li>
	<li>RDF para meta datos</li>
	<li>SMIL para crear presentaciones multimedia</li>
	<li>CSS y XSL para definir hojas de estilo</li>
	<li>XSLT para crear transformaciones de estilo</li>
	<li>PNG para gráficos (aunque algunos tipos se expresan mejor en JPG, que es una especificación que no es del W3C)</li> 
</ul>
</li>
</ul>';
$manual[112] = '<p>Dependiendo del lenguaje utilizado para construir la página, es posible que se estén utilizando elementos obsoletos o desaconsejados, que pueden suponer una barrera de acceso a algunos usuarios (por ejemplo, el elemento FONT que define unas determinadas características fijas para un texto, impidiendo que el usuario pueda modificarlo según sus necesidades).</p><p>Recuerde que <acronym title="HyperText Markup Language" lang="en">HTML</acronym> admite más elementos que XHTML y que las versiones Strict son más restrictivas que Transitional, por ejemplo.</p>';
$manual[113] = '<p>Que los usuarios puedan recibir los documentos según sus preferencias, significa, por ejemplo: en un determinado idioma, un determinado tipo de contenido, un determinado formato, etc.</p>
<ul>
<li>Los usuarios pueden preferir recibir los contenidos en su propio idioma, escuchar las páginas en vez de verlas, tener a su disposición distintas formas de presentación del contenido o recibir el contenido de forma apropiada por diversos medios como Braille o teléfono para sordos (TTY).</li>
<li>Para revisar esto, ver si se ofrece el contenido en varios idiomas, mediante un enlace o mediante negociación de contenido, para revisar esto último, cambiar el idioma de preferencia en el navegador y volver a entrar en la página, si el contenido aparece en el idioma elegido (por ejemplo, catalán) es que se está ofreciendo la versión idiomática mediante la negociación de contenido.</li>
<li>Si se ofrecen vídeos o presentaciones multimedia incrustadas, revisar si ofrecen subtítulos en varios idiomas.</li>
<li>Cuando se ofrezca la posibilidad de descargar un documento en un formato dado, deben ofrecerse otros formatos alternativos, como por ejemplo: <acronym title="HyperText Markup Language" lang="en">HTML</acronym>, doc, rtf, pdf, txt, etc. Comprobar si esto se hace así y preferiblemente en formatos no propietarios.</li>
<li>Si es posible, en el sitio debe ofrecerse un teléfono gratuito y funcional las 24 horas del día, en el que se pueda solicitar la información.</li>
</ul>';
$manual[114] = '<p>Si la página no cumple al menos con todos los pntos de prioridad 2 (nivel mínimo de accesibilidad requerido en toda Europa y la mayor parte de los países del mundo), ver si se ofrece un enlace a otra página que tenga el mismo contenido o funcionalidad, pero que sí use las tecnologías del <acronym title="World Wide Web Consortium" lang="en">W3C</acronym>, sea accesible y se actualice tan a menudo como esta que está revisando.</p>
<p>Nota: El punto pide crear otra página que sea accesible. NO pide, ni puede interpretarse como solución, el que haya otra página o versión "sólo texto".</p>';
$manual[121] = '<p>Los marcos pueden causar graves molestias especialmente a los usuarios de alguna ayudas técnicas, y en cualquier caso les son difíciles de manejar. Por esa razón, si se utilizan marcos es esencial que cada marco tenga un título lo más descriptivo posible del contenido que presentará.</p>';
$manual[122] = '<p>Es muy posible que aún incluyendo un título para cada marco, no sea obvio para el usuario cuál es su contenido y relación con los otros marcos. Por esta razón se pide que se describa esto en una página aparte. La URL de esa página debe indicarse con el atributo "longdesc" y, también, debe colocarse un enlace a ella como contenido del elemento NOFRAME.</p>';
$manual[123] = '<p>Los bloques de información demasiado largos dificultan su comprensión, especialmente a algunas personas con deficiencias cognitivas. Por esta razón y por simple lógica, conviene estructurar los documentos creando bloques de información adecuados a la misma.</p>';
$manual[124] = '<p>El atributo FOR de cada etiqueta &#x3C;LABEL&#x3E; debe coincidir con el atributo ID del control de formulario. A esto es a lo que se llama una asociación explícita. Esto es especialmente útil para quienes usan algunos lectores de pantalla que de esta manera relacionan la etiqueta con el control de formulario y pueden guiar al usuario en su interacción con ellos.</p>';
$manual[131] = '<p>Un enlace debe indicar de la forma más clara y sucinta posible a dónde apunta, qué encontrará el usuario si sigue ese enlace. Esto es especialmente importante para los usuarios de ayudas técnicas como los lectores de pantalla, y para las personas con dislexia y/o dificultades de apendizaje.</p>';
$manual[132] = '<p>Los metadatos son información sobre los contenidos de la página y sobre otras cuestiones relativas a ella y al sitio en el que se encuentra, como datos del autor, fecha de caducidad si la tiene, fecha de creación, etc. Facilitan la localización, del documento y de sus contenidos, en la Web.</p>
<p>Algunos metadatos proporcionan información de orientación importante para el usuario, otros pueden proporcionar información a los robots de búsqueda e indexación, otros proporcionan información a las aplicaciones de usuario sobre la temática de la página (por ejemplo, si es apropiada o no para niños), los derechos de autor, etc. La declaración de los metadatos puede hacerse mediante el elemento "meta" cuando se refieren a datos contenidos en el propio documento, mediante el elemento "link" cuando se refieren a datos contenidos en un documento externo, o referirse a un "profile" donde se define la propiedad y sus atributos legales, mediante el atributo "profile".</p>
<p>Son contenedores de metadatos, el elemento "title", el elemento "address", el elemento "meta", la declaración de tipo de documento (DTD), el elemento "link" y los elementos "del" e "ins", así como los atributos "title" y "cite".</p><p>Si la página forma parte de una serie, de una colección de documentos, por ejemplo si forma parte junto con otras de lo que podría ser un manual, un catálogo, etc.; debe utilizarse el elemento LINK para relacionarlas.</p>';
$manual[133] = '<p>Un mapa o índice de los contenidos del sitio facilita la localización de los contenidos y comprender la relación entre las distintas páginas que comprenden un sitio.</p>
<p>Para verificar este punto, hay que ver si el sitio ofrece un índice de contenidos o mapa del sitio, generalmente indicado con un enlace llamado "mapa". Si el sitio es muy pequeño, el propio menú de navegación actuará como índice de contenidos.</p>';
$manual[134] = '<p>Los mecanismos de navegación, los enlaces, iconos, los "menú", que pueden ser de definición, de situación o contextuales, son esenciales para la comprensión de la estructuación y navegación por las páginas, el sitio, y la situación del usuario en cada momento de su visita. Por ello es muy importante, para todos los usuarios pero especialmente para quienes tienen limitaciones para la lectura y aprendizaje, que se usen de manera consistente en todo el sitio, es decir, que no cambie su apariencia ni su comportamiento de una página a otra.</p>
<p>Para verificar la aplicación de este punto, hay que observar si los mecanismos de navegación, aparecen siempre en la misma ubicación, en caso de que se usen iconos, si éstos apuntan siempre al mismo recurso y, si el comportamiento de esos mecanismos es siempre el mismo.</p>';
$manual[135] = '<p>Si los elementos de navegación principales se ofrecen agrupados, en una "barra de navegación", se destacan y se facilita su localización. Para los usuarios, especialmente para quienes se ayudan de lectores de pantalla, esto es esencial pues de esta manera pueden evitarlos en vez de tener que oír repetidamente un montón de elementos que ya conocen y no desean escuchar.</p>
<p>Para revisar este punto, hay que ver si los elementos principales para la navegación por el sitio se presentan como una barra de navegación (agrupados), que puede estar conformada por iconos, por textos o por ambos.</p>';
$manual[136] = '<p>Si se agrupan los enlaces relacionados, será más fácil reconocerlos como barra de navegación, lo que facilitará su localización en cualquier página del sitio. Esto es especialmente importante para los usuarios que no pueden ver y para los que tienen dificultades de aprendizaje.</p>
<ul>
<li>Dado que una serie de enlaces a las secciones principales del sitio conforman una lista, deben marcarse como elementos de tal lista.</li>
<li>Lo ideal es que los botones o enlaces que conforman la barra de menú formen parte de un elemento &#x3C;map&#x3E; que lleve un título que identifique que su contenido es una barra de navegación. Esto facilitará a quienes usan aplicaciones de usuario que siguen la especificación para ellas, el saltar ese grupo de elementos.</li>
<li>Ver si los enlaces están relacionados entre sí, marcados como listas, y preferiblemente como parte de un elemento <map></li>
<li>Como aún no todas las aplicaciones de usuario son capaces de saltar a solicitud del usuario las agrupaciones de elementos, debe proporcionarse un enlace que cumpla esta función. El enlace no debe estar conformado por una imagen invisible, debe ser un texto y debe, cuando menos, revelarse al recibir el foco. Porque ese enlace será usado no sólo por personas ciegas sino por todos los usarios de lectores de pantalla y por quienes utilizan el teclado para navegar.</li>
</ul>';
$manual[137] = '<p>Si en el sitio se ofrece un sistema de búsqueda, es importante ofrecer mecanismos de búsqueda que se acomoden a varios niveles de habilidad y preferencia. La mayoría de las utilidades de búsqueda requieren que el usuario indique palabras clave para buscar términos, por lo que los usuarios con dificultades para deletrear y aquellos para los que no les es familiar el idioma empleado en el sitio, tendrán dificultades a la hora de encontrar lo que necesitan, si el buscador exige una ortografía perfecta. Los procesadores de búsqueda deben incluir un revisor ortográfico, ofrecer la "mejor presunción" como alternativa, ejemplos de búsquedas, búsquedas por similitud, etc.
</p>
<p>Para revisar este punto, si el sitio ofrece un buscador, habrá que utilizarlo para ver si ofrece opciones avanzadas de búsqueda.</p>';
$manual[138] = '<p>Los usuarios de lectores de pantalla (personas ciegas, con deficiencia visual o con algunas deficiencias cognitivas) suelen "hojear" las páginas, es decir, saltan de encabezado en encabezado y de párrafo en párrafo escuchando sólo unas pocas palabras del párrafo para determinar si realmente les interesa escucharlo completo. Eso es algo que en realidad hacemos todos los usuarios, aunque no utilicemos lectores de pantalla, cuando buscamos una determinada información y deseamos encontrarla lo más rápidamente posible.</p>
<p>Si la idea principal o asunto de cada párrafo aparece al inicio, se facilitará la comprensión del párrafo y la navegación rápida, hojear, la página.</p>';
$manual[139] = '<p>Si una serie de páginas constituyen un documento, el enlazarlas entre sí, de la manera que se explicará más adelante, facilitará su lectura sin conexión a Internet y la navegación dentro de él, a todos los usuarios y especialmente a quienes utilizan el teclado para navegar.</p>
<p>Si los documentos (las páginas) están relacionados entre sí, por ejemplo si constituyen una presentación, manual, folleto, etc.; además de los metatags para relacionarlos debe haber un "contador" que indique dónde se encuentra el usuario, por ejemplo: "Página 3 de 25" y botones o enlaces a las páginas anterior, posterior y tabla de contenidos o índice.</p>';
$manual[1310] = '<p>Para quienes usan lectores de pantalla, sería muy molesto tener que oír una serie de caracteres sin sentido cuando su lector se encuentra con un dibujo creado con caracteres <abbr title="código estándar norteamericano para el intercambio de información">ASCII</abbr>. Por esta razón es importante ofrecer un modo de saltar el dibujo y continuar con el resto de contenidos de la página.</p>';
$manual[141] = '<p>Un sitio Web puede ser visitado y puede contar entre "sus clientes" con personas con defeciencias cognitivas, personas con bajo grado de alfabetización, personas que no dominan el idioma, etc.; en definitiva con personas con limitaciones para la lectura.</p>
<ul>
<li>En los sitios dirigidos a un público amplio, los contenidos deben estar expresados en un lenguaje claro y sencillo, evitando anglicismos, lenguaje corporativo, etc. Siguiendo las siguientes pautas se incrementará la facilidad de lectura y comprensión:
<ol>
<li>Cuidar que los títulos y el texto de los enlaces sea lo más claro y exactos posible. Las palabras más importantes deben reflejar la idea y ser, entre aquellas con significado similar, las que resulten más comunes.</li>
<li>Especificar el tema de las oraciones o párrafos al principio de los mismos.</li>
<li>Limitar cada párrafo a una idea principal.</li>
<li>Evitar los giros idiomáticos, las expresiones y vocabulario no familiares (modismos, jerga).</li>
<li>Si se emplean palabras familiares con significados especiales, proporcionar explicaciones de las mismas.</li>
<li>Evitar la voz pasiva.</li>
<li>Evitar estructuras complejas en las oraciones.</li>
<li>En los enlaces usar frases concisas pero con suficiente significado para ser entendidas aún fuera de contexto.</li>
<li>La ortografía debe ser correcta.</li>
</ol>
</li>
</ul>';
$manual[142] = '<p>Los iconos, las ilustraciones, los vídeos y animaciones, no deben cumplir una función meramente decorativa. Su uso correcto incrementa la comprensión y facilidad de uso de un sitio Web, para todos los usuarios, pero especialmente para quienes tienen dificultades de aprendizaje o, por ejemplo, para las personas con sordera prelocutiva.</p>
<p>Por ejemplo, una gráfica que acompaña a la presentación de datos estadísticos los hará más fáciles de comprender, para todos. Un icono que represente una determina sección del sitio, será más f´cil de recordar y muchas veces de comprender que una palabra que puede no tener mucho sentido para alguien que no conoce bien el idioma en el que está escrito el sitio o para alguien con dificultades de lectura o de concentración.</p>
<p>Para revisar este punto, hay que valorar si en la página se hace un uso apropiado de iconos y de sonidos que acompañan a acciones, la ilustración de los contenidos con imágenes, vídeos, animaciones y/o sonidos.</p>';
$manual[143] = '<p>Un estilo de presentación consistente en cada una de las páginas de un sitio, permite a los usuarios localizar más fácilmente el contenido importante. Esto ayuda a las personas con problemas de aprendizaje y lectura, pero también hace la navegación más fácil para todos los usuarios. La predecibilidad incrementará la probabilidad de que las personas encuentren la información en su sitio y les facilitará el evitar la que deseen.</p>
<ul>
<li>Los mecanismos de navegación y su ubicación, la maquetación, los colores, la ubicación de los bloques de texto que se mantienen uniformes entre páginas, permite advertir inmediatamente cuándo se ha entrado en el sitio... y también cuándo se lo ha abandonado.</li>
<li>Los mecanismos de navegación y pistas visuales o textuales que se proporcionan en todas las páginas permiten minimizar los esfuerzos del usuario para saber cuándo ha llegado al final del contenido o qué información adicional puede encontrar.</li>
</ul>
<p>Para revisar y valorar la aplicación de este punto hay que comparar la página que se está revisando con otras del mismo sitio.</p>';
?>
