<?php
$texto['dona_alt'] = 'Faça a sua doação agora: Contribua para o desenvolvimento do HERA';
$texto['intro_h1'] = 'O que é o HERA?';
$texto['intro_a'] = '<strong>HERA</strong> é uma ferramenta para rever a acessibilidade das páginas Web de acordo com as recomendações das <em>Directrizes de Acessibilidade para o Conteúdo Web 1.0</em> (<a href="http://www.w3.org/TR/WCAG10/" title="Web Content Accessibility Guidelines 1.0" hreflang="en">WCAG 1.0</a>). O <strong>HERA</strong> efectua uma análise automática prévia da página e disponibiliza informação dos erros encontrados <em>(detectáveis de forma automática)</em> e quais os pontos de verificação que devem ser revistos  manualmente.';
$texto['intro_b'] = 'A revisão manual é imprescindível para comprovar realmente se a página é acessivel. Para poder levar acabo esta verificação manual é necessário conhecer as directrizes de acessibilidade, saber de que forma fazem, os utilizadores, uso das ajudas técnicas e ter alguma experiência em desenho e desenvolvimento de páginas Web.';
$texto['intro_c'] = '<strong>HERA</strong> facilita a revisão manual, proporcionando informação sobre os elementos a verificar, instruções de como realizar esse controlo e duas visões modificadas da página <em>(uma visão gráfica, outra do código HTML)</em> com os elementos mais importantes destacados com icones e cores diferenciadoras.';
$texto['intro_d'] = '<strong>HERA</strong> disponibiliza um formulário que permite modificar os resultados automáticos, agregar comentários a cada um dos pontos de verificação e indicar o nome do revisor. Também é possível gerar um relatório final sobre a revisão, para imprimir ou descarregar, em diversos formatos: (<acronym title="Extensible HyperText Markup Language" lang="en">XHTML</acronym>, <acronym title="Resource Description Framework" lang="en">RDF</acronym> e <acronym title="Portable Document Format" lang="en">PDF</acronym>).';
$texto['intro_e'] = '<strong>Importante: </strong> Os dados ficarão guardados na base de dados do <strong>Sidar</strong> durante 7 (sete) dias a partir do início da revisão. Durante esse período é possível retomar um trabalho utilizando a URL da página resumo, que contém o identificador da revisão.';
$texto['help_h1'] = 'Ajuda do HERA';
$texto['help_a'] = 'Uma vez indicada a página a rever, o <strong>HERA</strong> mostra um resumo com a informação obtida na análise automática e define um  resultado para cada ponto de verificação.';
$texto['help_img_1'] = 'Visão do resumo de resultados.';
$texto['help_dd_bien'] = 'Quando a análise pode detectar, sem quaisquer dúvidas, que a página cumpre com os requisitos de acessibilidade desse ponto.';
$texto['help_dd_duda'] = 'Quando a análise não pode confirmar, com toda a certeza, o cumprimento do ponto e se requer a interpretação do utilizador. Neste caso, <strong>HERA</strong> disponibiliza opções para efectuar a <a href="#op">revisão manual</a>.';
$texto['help_dd_mal'] = 'Quando a análise pode detectar que a página não cumpre, parcial ou totalmente, com os requisitos de acessibilidade.';
$texto['help_dd_na'] = 'Quando o ponto faz referência a elementos que não se encontram presentes na página.';
$texto['help_dd_parcial'] = 'Quando o cumprimento dos requisitos de acessibilidade não se verifica totalmente.';
$texto['help_dd_nose'] = 'Quando o revisor não pode confirmar se o ponto de controlo se cumpre ou não.';
$texto['help_b'] = 'Nesta etapa existe sempre uma certa quantidade de pontos a verificar pelo utilizador. Uma vez que o utilizador/revisor tenha comprovado um ponto, pode utilizar o formulário para modificar o seu resultado. O formulário oferece ainda outros dois, possíveis resultados, que se adicionam aos anteriores.';
$texto['help_img_2'] = 'Visão do quadro resumo dos resultados incluíndo as revisões feitas pelo utilizador.';
$texto['help_h2_a'] = 'Revisão manual';
$texto['help_h2_b'] = 'Barra de icones';
$texto['help_c'] = 'Cada ponto pode abarcar um ou vários itens a rever, em que cada um dos quais terá o seu próprio resultado. Se os resultados dos itens não coincidem entre sí, o resultado global do ponto decide-se pelo item com o pior resultado. Por exemplo: se um dos itens está "incorrecto", o resultado do ponto também o será, quaisquer que sejam os resultados dos restantes itens do ponto.';
$texto['help_img_3'] = 'Visão do formulário de revisões de um ponto.';
$texto['help_d'] = '<strong>HERA</strong> oferece várias opções para ajudar o revisor a verificar cada item. Quando resulta possível, indicam-se os elementos encontrados na página e o que se deve rever. Na continuação deste texto, adicionam-se três icones para as respectivas ajudas.';
$texto['help_icon_a'] = 'Mostra/esconde as instruções necesarias para efectuar a revisão.';
$texto['help_icon_b'] = 'Mostra numa janela à parte a página, com os elementos a rever destacados mediante icones, molduras de cor e, geralmente, mostra o código de cada elemento. Como estes agregados à página original se podem sobrepor a outros elementos, existe uma opção para activar e desactivar as folhas de estilo da página.';
$texto['help_icon_c'] = 'Mostra numa janela à parte o código da página, com os elementos a rever destacados mediante icones e molduras de cor.';
$texto['help_icon_d'] = 'Abre a página numa nova janela.';
$texto['help_icon_e'] = 'Abre uma nova janela para mostrar o código original da página.';
$texto['help_icon_f'] = 'Regressa à página resumo, a partir da qual é possível eleger o modo de navegar pelos pontos de verificação.';
$texto['help_icon_g'] = 'Mostra/esconde os textos de ajuda para cada um dos pontos de verificação.';
$texto['help_icon_h'] = 'Mostra/esconde o formulário para modificar os resultados de cada ponto.';
$texto['help_icon_i'] = 'Leva-o ao formulário que lhe permite solicitar o relatório da revisão. Este relatório pode-se obter em diversos formatos: XHTML, RDF e PDF.';
$texto['help_e'] = 'Deste modo, utilizando ambas as visões da página como ajuda, o revisor poderá identificar os elementos importantes, valorar a sua utilização e  decidir o resultado para cada item do ponto.';
$texto['help_f'] = 'Dois icones, anexados junto à URL da página em revisão, permitem abrir a página original e ver o seu código, em ambos os casos sem nenhum dos agregados que efectuam as opções anteriores.';
$texto['help_h3_estil'] = 'Estilos de trabalho';
$texto['help_estil_a'] = 'A revisão completa pode fazer-se navegando pela tabela de resultados ou seguindo a numeração das directrizes.';
$texto['help_h41_estil'] = 'Navegar pelas directrizes';
$texto['help_img_4'] = 'Detalhe do acesso à navegação por directrizes.';
$texto['help_estil_b'] = 'A partir da página Resumo, acede-se à navegação por directrizes, que se apresentam mediante botões posicionados no final da mesma. Uma vez eleita esta opção, aparecerão os pontos de controlo, da directriz seleccionada, para serem revistos. Para facilitar a navegação pelas directrizes, aparecem na parte superior da página de revisão os botões com o número de cada uma delas.';
$texto['help_h42_estil'] = 'Navegar pelos resultados';
$texto['help_img_5'] = 'Detalhe do acesso à navegação por resultados.';
$texto['help_estil_c'] = 'A navegação por resultados acede-se a partir da tabela resumo dos mesmos. Esta forma de navegação pode tornar mais animada a tarefa pois vai-se vendo claramente os pontos que se vão resolvendo, especialmente importante quando o revisor trabalha sobre o seu próprio sítio Web e pode corrigir as falhas encontradas. Na parte superior da página de revisão aparece a tabela que vai mostrando os resultados com as modificações indicadas pelo revisor.';
$texto['help_h3_informe'] = 'Gerar o relatório';
$texto['help_informe_a'] = 'Ao pressionar o icone para solicitar o relatório aparecerá um formulário no qual o revisor pode indicar o seu nome, endereço de correio electrónico, o título que quer dar ao relatório, e um campo para introduzir um comentário geral.';
$texto['help_informe_b'] = 'Pode então seleccionar-se que tipos de resultados (A verificar, correcto, incorrecto, não aplicável, parcial, não sei) se desejam incluir no relatório, ou se se deseja incluir a todos.';
$texto['help_informe_c'] = 'Uma vez feito isto, pode-se eleger o ou os tipos de relatórios a gerar, como veremos a seguir.';
$texto['help_h4_infor1'] = 'Relatório <acronym title="Hypertext Markup Language" xml:lang="en" lang="en">HTML</acronym>';
$texto['help_img_6'] = 'Visão do relatório em formato html.';
$texto['help_informe_d'] = 'No formulário existe um botão para ver o relatório em formato <acronym title="Hypertext Markup Language" xml:lang="en" lang="en">HTML</acronym>, que abrirá uma nova janela do navegador com o relatório nesse formato, o que supõe que pode imprimir-se directamente a partir dali, utilizando o botão ou a opção do menú para imprimir do navegador que se está a usar.';
$texto['help_informe_e'] = 'Também existe um botão especial para descarregar o relatório em formato html. Desta forma, podem guardar-se com o nome que se deseje, para publicá-los na Web ou para publicá-los em papel. O revisor pode então, se o desejar, criar uma folha de estilos especial para a impressão, de maneira que se ajuste ao papel timbrado da sua empresa e anexá-la aos ficheiros em formato html descarregados.';
$texto['help_h4_infor2'] = 'Relatório <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym>';
$texto['help_img_7'] = 'Visão de um relatório em rdf apresentado mediante o visualizador de relatórios.';
$texto['help_informe_f'] = 'HERA gera também o relatório em formato <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym>, contribuindo assim para que tenhamos e seja possível aproveitar as possibilidades de uma Web semanticamente mais rica.';
$texto['help_informe_g'] = 'O botão "Ver o relatório <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym>" abrirá uma nova janela do navegador com o conteúdo do relatório em linguagem EARL e em formato RDF. É possível que algum utilizador não consiga ver directamente no seu navegador este relatório se estiver a usar uma aplicação antiga, incapaz de suportar XML, mas não tem que se preocupar, uma vez que estes relatórios não estão pensados para serem lidos por humanos mas sim pelas máquinas. De qualquer forma, pode utilizar, se assim o desejar, o <a title="Exemplos de aplicações: descarga do script de visualização de relatórios." href="http://www.sidar.org/informes/">script de visualização de relatórios</a>, e poderá publicar na sua própria Web, de maneira que sejam legíveis e atractivos para os utilizadores humanos e de acordo com o aspecto geral do seu próprio sítio Web.';
$texto['help_informe_h'] = 'O botão "Descarregar o relatório <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym>" permite, como o seu nome indica, descarregar o ficheiro com o relatório gerado, para o guardar e o publicar onde  como deseja. O revisor ou equipa de revisão pode optar por usar o script anteriormente mencionado, ou publicar directamente os ficheiros <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym> colocando um link a partir de cada uma das páginas que foram revistas. Inclusivamente poderá gerar um gráfico da revisão, socorrendo-se do <a href="http://www.w3.org/RDF/Validator/" hreflang="en">revisor de sintaxes <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym></a>, do W3C.';
$texto['help_h4_infor3'] = 'Relatório em <acronym title="Portable Document Format" xml:lang="en" lang="en">PDF</acronym>';
$texto['help_img_8'] = 'Visão de um relatório em formato PDF.';
$texto['help_informe_i'] = 'Uma opção adicional, consiste em gerar o relatório em formato <acronym title="Portable Document Format" xml:lang="en" lang="en">PDF</acronym>. Trata-se de uma versão <em>em bruto</em>, que permite ao utilizador do   HERA descarregar e efectuar as marcas, estructuração, e modificações oportunas para o publicar nesse mesmo formato, com o desenho de maquetação que prefere. (Por favor, não se esqueça de estruturar o documento antes de o publicar, para que seja o mais acessível possível).';
$texto['help_h3_declara'] = 'Declarar ter feito a revisão com o HERA';
$texto['help_declara_a'] = 'Uma vez feita a revisão e, no seu caso, as modificações oportunas para alcançar o nível de acessibilidade desejado, convém declarar que o fez; e para isso, use um dos seguintes icones enlaçados, idealmente, com o relatório em formato <acronym title="Resource Description Framework" xml:lang="en" lang="en">RDF</acronym> gerado pelo HERA. Desta maneira os robots serão capazes de indexar a sua página entre as que cumprem com determinadas características de acessibilidade ou, noutro caso, com a <a href="http://www.w3.org/WAI/WCAG1AA-Conformance">página de conformidade com as Directrizes de Acessibilidade para o Conteúdo Web 1.0 da <acronym title="Web Accessibility Initiative" xml:lang="en" lang="en">WAI</acronym></a>.';
$texto['help_declara_b'] = 'Pode eleger um dos seguintes icones de estilo "clássico" de acordo com o nível alcançado:';
$texto['help_declara_c'] = 'Ou eleger o icone apropriado de estilo mais actual:';
$texto['help_declara_d'] = 'Ou criar um dos seguintes botões utilizando unicamente folhas de estilo em Cascata:';
$texto['help_declara_e'] = '<ul class="navlistpie">
<li class="botonhera"><a href="http://www.sidar.org/hera/" title="HERA: Revendo com Estilo a Acessibilidade."><span class="hera">HERA</span> <acronym title="Web Accessibility Initiative" lang="en" class="spec">WAI</acronym>-<acronym title="Conforme com o nível A de Acessibilidade" class="conform">A</acronym></a></li>
<li class="botonhera"><a href="http://www.sidar.org/hera/" title="HERA: Revendo com Estilo a Acessibilidade."><span class="hera">HERA</span> <acronym title="Web Accessibility Initiative" lang="en" class="spec">WAI</acronym>-<acronym title="Conforme com o nível Duplo A de Acessibilidade" class="conform">AA</acronym></a></li>
<li class="botonhera"><a href="http://www.sidar.org/hera/" title="HERA: Revendo com Estilo a Acessibilidade."><span class="hera">HERA</span> <acronym title="Web Accessibility Initiative" lang="en" class="spec">WAI</acronym>-<acronym title="Conforme com o nível Triplo A de Acessibilidade" class="conform">AAA</acronym></span></a></li>
</ul>';
$texto['help_declara_f'] = 'Os estilos usados nesses botões estão definidos na <a title="Descarga la folha de estilos que define os botões do HERA." href="botonhera.css">botonhera.css</a>.';
$texto['help_h3_integra'] = 'Incorporar o HERA no seu navegador';
$texto['help_integra_a'] = 'Os desenvolvedores e consultores irão considerar útil provocar a execução do HERA directamente a partir de um botão incorporado na interface do seu navegador. Para isso oferemos-lhe aquí várias opções:<br />
<a href="http://www.sidar.org/extension/" hreflang="es"><strong>Extensions for the Mozilla family browsers</strong></a>: The users of the Mozilla family browsers (Firefox, Flock, Netscape, Safari, etc.) they can install <a href="http://www.sidar.org/extension/hera/heraext.xpi"><strong>HERA-Extension</strong></a>, that allows to initiate the oage or frame revision, with a single click, that is visualizing then. The extension installs a bar and a button in the state bar of the browser.';
$texto['help_h4_integra1'] = 'Favelets';
$texto['help_integra_b'] = 'As <span xml:lang="en" lang="en">Favelets</span> ou <span xml:lang="en" lang="en">Bookmarklets</span> são pequenos fragmentos de <span xml:lang="en" lang="en">JavaScripts</span> incrustados num <span lang="en">link</span> e que permitem anexar a sua funcionalidade à lista de favoritos do navegador.';
$texto['help_integra_c'] = 'Para o seu funcionamento é necessário o suporte de <span xml:lang="en" lang="en">JavaScript</span> no navegador. A maioría dos <span lang="en">Favelet</span> funcionam bem no Internet Explorer 5.0 ou superior e  nos navegadores da familia Mozilla 1.0 ou superior (Incluindo <span lang="en">Netscape</span> e <span lang="en">Firefox</span>).';
$texto['help_integra_d'] = 'Os que aquí apresentamos foram testados no Internet Explorer 6.0, Mozilla 1.7.7, Mozilla 1.8a6, Netscape 7.2, Firefox 1.0.4, Opera 7.50 e Opera 8.0.';
$texto['help_integra_e'] = 'Para ter um acesso directo ao <strong>HERA</strong> a partir do seu  navegador, bastará arrastar um ou vários dos seguintes <span lang="en">links</span> para a barra de favoritos do mesmo. Criar-se-á um botão ou acesso directo. Assim, cada vez que deseje usá-lo bastará pressionar ou seleccionar o botão que deseja utilizar.';
$texto['help_integra_f'] = '<dl>
<dt><a href="javascript:void(window.location=&#039;http://www.sidar.org/hera/?url= &#039;+escape(window.location))"><img src="img/genhera.gif" alt="" width="16" height="16" style="border: none; padding-right: 1em;" />HERA: Rever página actual</a></dt>
<dd>Chama o HERA para que se efectue a revisão da página que tem o  foco activo no navegador, fazendo-o na mesma janela.</dd>
<dt><a href="javascript:void(window.open(&#039;http://www.sidar.org/hera/?url=&#039;+escape(window.location),&#039;_blank&#039;));"><img src="img/genhera.gif" alt="" width="16" height="16" style="border: none; padding-right: 1em;" />HERA: Rever página actual numa nova janela</a></dt>
<dd>Chama o HERA para efectuar a revisão da página que se está a visitar, e a revisão faz-se numa nova janela.</dd>
<dt><a href="javascript:void(q=prompt(&#039;Validate Page:&#039;,&#039;&#039;));if(q)void(window.location=&#039;http://www.sidar.org/hera/?url=&#039;+escape(q))"><img src="img/genhera.gif" alt="" width="16" height="16" style="border: none; padding-right: 1em;" />Rever com HERA</a></dt>
<dd>Abre um quadro de diálogo no qual se pode indicar a direcção da página que se quer rever e efectua a revisão na janela actualmente activa.</dd>
<dt><a href="javascript:void(q=prompt(&#039;Validate Page:&#039;,&#039;&#039;));if(q)window.open(&#039;http://www.sidar.org/hera/?url=&#039;+escape(q));void%200"><img src="img/genhera.gif" alt="" width="16" height="16" style="border: none; padding-right: 1em;" />Rever com HERA numa nova janela</a></dt>
<dd>Abre um quadro de diálogo para indicar a direcção da página que se quer rever e abre uma nova janela com os resultados.</dd>
</dl>';
$texto['help_integra_f1'] = 'Estes <span lang="en">Favelets</span> ou <span lang="en">Bookmarklets</span> foram criados por <span lang="es">Emmanuelle Gutiérrez y Restrepo</span>, com a colaboração de <span lang="fr">Vincent Tabard</span> e da equipa da <span lang="en">Opera Software</span>.';
$texto['help_h4_integra2'] = 'Anexar HERA à "<span xml:lang="en" lang="en">Web Developer Extension</span>"';
$texto['help_integra_g'] = 'Os desenvolvedores que utilizam <span lang="en">Mozilla</span> ou <span lang="en">Firefox</span> estão acostumados a usar uma extensão criada por  <a href="http://chrispederick.com/" hreflang="en"><span xml:lang="en" lang="en">Chris  Pederick</span></a> chamada "<a href="http://chrispederick.com/work/firefox/webdeveloper/" hreflang="en"><span lang="en">Web Developer Extension</span></a>" e que anexa um menú e uma barra de ferramentas com uma série de funcionalidades úteis para comprovar determinados aspectos de uma página Web.';
$texto['help_integra_h'] = 'A extensão oferece acesso directo a uma série de revisores e é muito fácil anexar uma opção para rever com HERA:';
$texto['help_integra_i'] = 'Uma vez instalada a extensão, ao pressionar o botão direito do rato sobre qualquer página aberta, seleccione "<span xml:lang="en" lang="en">Web Developer</span>" &gt;&gt; "<span xml:lang="en" lang="en">Options</span>" &gt;&gt; "<span xml:lang="en" lang="en">Options.</span>" (Se instalou a versão em português as opções  serão "<span lang="pt">Opções</span>" &gt;&gt; "<span lang="pt">Opções...</span>".';
$texto['help_img_integrai'] = 'Detalhe do menú contextual com as opções do <span lang="en">Web Developer</span>';
$texto['help_integra_i2'] = 'No quadro de diálogo que se abre, seleccione "<span xml:lang="en" lang="en">Tools</span>" e pressione o botão "<span xml:lang="en" lang="en">Add</span>" (Em português: "<span lang="pt">Ferramentas</span>" &gt;&gt; "<span lang="pt">Anexar</span>").';
$texto['help_img_integrai2'] = 'Detalhe do quadro de diálogo de opções do <span lang="en">Web Developer</span>';
$texto['help_integra_i3'] = 'Abrir-se-á um quadro de diálogo no qual se deve indicar o nome da ferramenta (neste caso, HERA) e um campo para a URL em que tem de colocar: "http://www.sidar.org/hera/?url="; também se pode indicar um atalho de teclado para activar a revisão com HERA.';
$texto['help_img_integrai3'] = 'Detalhe do quadro de diálogo para anexar ferramentas ao <span lang="en">Web Developer</span>';
$texto['help_integra_i4'] = 'E já está. A partir de agora, bastará pressionar o botão direito do rato sobre a página que se está a visitar e seleccionar: <span xml:lang="en" lang="en">Web Developer</span> &gt;&gt; <span xml:lang="en" lang="en">Tools</span> &gt;&gt; HERA, ou pressionar a combinação de teclas indicadas para o atalho anteriormente definido, e dar-se-á início à revisão.';
$texto['help_img_integrai4'] = 'Detalhe do menú contextual <span lang="en">Web Developer</span> com HERA incorporado';
$texto['help_integra_j'] = '(As imagens que ilustram este processo foram cedidas por <a href="http://www.torresburriel.com/weblog/index.php?p=547"><span lang="es">Daniel Torres Burriel</span></a>.)';
$texto['help_h4_integra3'] = 'Anexar HERA a <span xml:lang="en" lang="en">Opera W3-Dev Menu</span>';
$texto['help_integra_k'] = '<a href="http://tobyinkster.co.uk/" hreflang="en"><span lang="en">Toby Inkster</span></a> criou um menú especial para desenvolvedores que utilizam Opera. O <a href="http://tobyinkster.co.uk/opera" hreflang="en"><span lang="en">Opera W3-Dev Menu</span></a>, oferece acesso directo a ferramentas de revisão e documentação de interesse sobre standards, acessibilidade e usabilidade (Até ao momento tudo isto está em inglês, mas estamos a traduzi-lo).';
$texto['help_img_9'] = 'Detalhe do menú para desenvolvedores de Opera com HERA incorporado na sua interface.';
$texto['help_integra_l'] = 'O menú instala-se directamente a partir da página de descarregar e pode anexar-se-lhe o HERA muito facilmente. Para isso, uma vez instalado, basta editar o ficheiro "v3dev-1.99.ini" que se encontrará no separador  "menu" do directório "<span lang="en">profile</span>" da instalação do Opera. (Como a instalação pode ser muito diferente consoante a configuração do sistema operativo, o mais fácil será localizar o ficheiro mediante o motor de busca do sistema).';
$texto['help_integra_m'] = 'Uma vez localizado o ficheiro, pode abri-lo com qualquer editor de texto, e na linha 55 agarrar a seguinte cadeia de texto: «Item, "HERA" = Go to page, "http://www.sidar.org/hera/?url=%u"». Se o editor não mostrar os números de linha, basta localizar o texto: «[Actions Menu]» e agarrar a cadeia anteriormente mencionada: "----1". Esta operação não deve ser feita com o Opera aberto. Uma vez editado o ficheiro, pode abrir o Opera e aparecerá o menú com o acesso directo ao HERA que permitirá rever a página que estemos a visitar nesse momento.';
$texto['help_g'] = 'Se tem dúvidas sobre como efectuar as revisões, ou sugestões para melhorar esta ferramenta, envíe uma mensagem a: <a href="mailto:hera@sidar.org">hera@sidar.org</a>.';
$texto['info_h1'] = 'Informação sobre o HERA';
$texto['info_indice'] = '<ol class="indice">
	<li><a href="#info_intro">Introdução</a></li>
	<li><a href="#info_princi">Principio e fim</a></li>
	<li><a href="#info_cola">Colaborar</a></li>
	<li><a href="#info_reco">Reconhecimentos</a></li>
	<li><a href="#info_traduc">Tradutores</a></li>
</ol>';
$texto['info_a'] = 'A <a href="http://www.sidar.org/" lang="es" xml:lang="es" name="info_intro">Fundación Sidar</a> coloca à  disposição da comunidade de desenvolvedores, disenhadores e público em geral, de forma gratuita, esta ferramenta para facilitar a revisão da acessibilidade das páginas e sítios Web. <strong>HERA</strong> foi desenhado e desenvolvido por <a href="http://www.sidar.org/que/ge/cb.php">Carlos Benavídez</a>, com a colaboração de <a href="http://www.sidar.org/que/ge/egyr.php" lang="es" xml:lang="es">Emmanuelle Gutiérrez y Restrepo</a> e <a href="http://www.sidar.org/que/ge/cmccn.php" lang="en" xml:lang="en">Charles McCathieNevile</a>, especialmente para a <strong lang="es" xml:lang="es">Fundación Sidar</strong>.';
$texto['info_h2_sobre'] = 'Princípio e fim';
$texto['info_origen'] = '<a name="info_princi"></a> De onde é originário o nome de <strong>HERA</strong>? No início do ano 2003, a Fundação Sidar lançou o <a href="http://www.sidar.org/edipo/">Edipo</a>, uma ferramenta para a criação de folhas de estilo pessoais e, já naquela altura, pensámos na criação de um utilitário "irmão" baseado na aplicação de folhas de estilo para facilitar a revisão da acessibilidade. Uma vez que Edipo é o nome de um personagem mitológico, procurámos algo similar para esta nova aplicação e surgiu o de HERA que, para além de ser o de outra personagem feminina, corresponde o acrónimo de: Folhas de Estilo para a Revisão da Acessibilidade. A primeira versão do HERA baseia-se precisamente na aplicação de folhas de estilo para facilitar a revisão manual da acessibilidade. Esta nova versão já não depende disso, pois pretendiamos que pudesse funcionar em qualquer navegador, incluindo naqueles que não suportam algumas propriedades das folhas de estilo, mas depois de uma consulta aos seus utilizadores decidimos manter o nome de HERA.';
$texto['info_define'] = 'O objectivo de <strong>HERA</strong> é facilitar o trabalho a quem deseja ou tem a missão de rever a acessibilidade de uma página ou sítio Web. A revisão da acessibilidade nunca pode estar completa sem uma revisão manual. As ferramentas de revisão automática apenas podem detectar determinados elementos e atributos mas não podem assegurar que se esteja a utilizar apropriadamente. Por isso, é imprescindivel a participação de um ser humano que possa comprovar os elementos e atributos que não podem ser revistos automaticamente e se os mesmos se estão a aplicar correctamente às directrizes de acessibilidade.';
$texto['info_difiere'] = 'Assim, o <strong>HERA</strong> é uma ferramenta para revisão <strong>manual</strong> da acessibilidade, apesar de esta nova versão oferecer também a <strong>revisão automática</strong> de maneira a facilitar o trabalho do revisor, indicándo-lhe quais os pontos que, <strong>com segurança</strong>, estão em falta, quais os que, <strong>com segurança</strong>, se encontram bem, quais os que não se aplicam nessa página em concreto e, quais os pontos que, <strong>obrigatoriamente</strong>, devem ser revistos por mão humana.';
$texto['info_proceso'] = '<strong>HERA</strong> possibilita ao revisor a localização dos erros através de uma visão da página com os elementos a necessitar de revisão destacados usando icones, molduras de cor e, geralmente, o código de cada elemento; outra visão do código fonte da página mas na qual se destacam os elementos susceptíveis de conter erro; uma ferramenta adicional para a revisão do contraste das cores usadas, e visões complementares da página e do seu código fonte. Para além disso, disponibilizam-se instruções em linha sobre aquilo em que o revisor tem de enfocar a sua atenção quando analisa a aplicação de cada um dos pontos, lembretes e uma ajuda complementar e extensa que incluirá, na sua versão futura, exemplos gráficos da aplicação das Directrizes de Acessibilidade. Na página de Ajuda encontrará mais informação sobre cómo funciona HERA.';
$texto['info_h2cola'] = 'Colaborar';
$texto['info_b'] = '<a name="info_cola"><strong>HERA</strong></a> é um utilitário escrita em <acronym title="Hypertext Preprocessor" lang="en">PHP</acronym> e, como todos os projectos da <strong lang="es" xml:lang="es">Fundación Sidar</strong>, é uma aplicação de código aberto, em cujo desenvolvimento pode colaborar qualquer pessoa adicionando melhorias, modificações, traduções, correcção de erros, documentação, etc. Para estabelecer o contacto con a Equipa de Desenvolvimento, envíe uma mensagem a: <a href="mailto:hera@sidar.org">hera@sidar.org</a>.';
$texto['info_c'] = 'O <a href="%s" title="Código fonte de HERA.">código fonte</a> do <strong>HERA</strong> distribui-se debaixo dos termos da <a href="http://www.sidar.org/legal/2003/gpl.html">Licença Pública Geral</a> (<acronym title="Licença Pública Geral">GPL</acronym>) da <a href="http://www.gnu.org/philosophy/license-list.html#GPLCompatibleLicenses" hreflang="en"><span lang="en" style="font-style:italic" lang="en" xml:lang="en">Free Software Foundation</span></a> e a definição da  <a href="http://www.opensource.org/docs/definition.php" hreflang="en"><span lang="en">Open Source</span></a>. Se necessita de mais informação sobre o conceito de "software livre", pode ler a nossa <a href="http://www.sidar.org/legal/2003/copy.php">licença de software</a>.';
$texto['info_d'] = 'Por outro lado, confiamos em que quem usar o <strong>HERA</strong> como apoio às suas revisões, pessoais ou profissionais, com ou sem lucro, declare a sua utilização. Pode utilizar os icones, que indicam que a página cumpre com um determinado nível de conformidade.';
$texto['info_masicos'] = 'Na página de Ajuda encontrará icones opcionais, os quais provavelmente se adequaram mais ao estilo da sua página e que poderá, inclusivamente, personalizar.';
$texto['info_e'] = 'Aconselhamos que os icones fiquem enlaçados com o relatório gerado com o HERA, e que no mesmo se disponibilizem os dados da pessoa que efectuóu a revisão e a data em que a realizou.  Também, uma vez que se poderão produzir erros na modificação das páginas, seria desejável que o icone represente o compromisso de manter a qualidade alcançada e de solucionar qualquer inconveniente que possa vir a ser detectado.';
$texto['info_h2'] = 'Agradecimentos';
$texto['info_f'] = '<a name="info_reco">Muitos</a> contribuiram, de uma ou de outra forma, para o desenvolvimento do  <strong>HERA</strong>. Principalmente aqueles que são membros e colaboradores do <strong>Sidar</strong> que constituem o seu principal grupo de trabalho: <strong lang="es">Emmanuelle Gutiérrez y Restrepo</strong>, <strong lang="en">Charles McCathieNevile</strong>, <strong lang="es">Loïc Martínez Normand</strong>, <strong lang="es">Rafael Romero</strong> e <strong lang="pt">Jorge Fernandes</strong>.';
$texto['info_g'] = 'O grupo de pessoas que realizou os primeiros testes do <strong>HERA</strong>: <strong lang="es">Martín Baldassarre</strong>, <strong lang="fr">Vincent Tabard</strong>, <strong lang="es">David Arango</strong>, <strong lang="es">Fernando Gutiérrez</strong>, <strong lang="es">José Luis Fuertes</strong> e <strong lang="en">Tom Croucher</strong>.';
$texto['info_h'] = '<strong>Daniel Low</strong> deu-nos os primeiros conselhos como utilizador e <strong lang="es">Ramiro Benavídez</strong> trabalhou no desenvolvimento da função para efectuar a revisão do contraste das cores.';
$texto['info_i'] = '<strong>Olivier Plathey</strong> disponibilizou <a href="http://www.fpdf.org/">FPDF</a>, que permite gerar documentos PDF directamente a partir de PHP.';
$texto['info_h2tradu'] = 'Traduções';
$texto['info_a_1'] = 'O <a name="info_traduc"><strong>HERA</strong></a> está a ser traduzido para vários idiomas tendo despertado o interesse internacional.';
$texto['info_trada'] = 'A tradução para %s está a cargo de:';
$texto['info_tracola'] = 'Se desejar colaborar traduzindo os actuais ou outros idiomas, por favor, envíe uma mensagem para <a href="mailto:transhera@sidar.org" title="Envía uma mensagem à lista de tradutores do HERA.">transhera@sidar.org</a>.';
$texto['code_h1'] = 'Código fonte de HERA';
$texto['code_p'] = 'Os arquivos podem-se ver/descarregar individualmente. Se desejar fazer alguma consulta a este respeito, por favor, envíe uma mensagem para: <a href="mailto:hera@sidar.org">hera@sidar.org</a>.';
$texto['code_op_a'] = 'Ver';
$texto['code_op_b'] = 'Descarregar';
$texto['code_li_a'] = '<em>Directório /inc/...</em><br /><span class="small">Arquivos incluidos dinamicamente.</span>';
$texto['code_li_b'] = '<em>Directório /lang/...</em><br /><span class="small">Cada tradução fica armazenada num directório identificado com o código do idioma.</span>';
$texto['code_1'] = 'A página inicial de cada idioma identifica-se através da extensão que dispõe do código de idioma.';
$texto['code_2'] = 'Mostra a página (no modo gráfico ou código) destacando os elementos a verificar manualmente.';
$texto['code_3'] = 'Gerar o relatório em XHTML, RDF ou PDF, para imprimir ou descarregar.';
$texto['code_4'] = 'Utilidade adicional para verificar o contraste das cores da página.';
$texto['code_5'] = 'Folha de estilo.';
$texto['code_6'] = 'Folha de estilo utilizada nas visões da página.';
$texto['code_7'] = 'Algumas funções básicas.';
$texto['code_8'] = 'Decida as acções a levar a efeito, escreva o cabeçalho e o pé de página.';
$texto['code_9'] = 'Obtém o conteúdo da página a rever.';
$texto['code_10'] = 'Analisa o conteúdo da página e obtém os resultados automáticos.';
$texto['code_11'] = 'Mostra o resumo dos resultados e o sistema de navegaçao (por pontos ou por directrizes).';
$texto['code_12'] = 'Mostra os pontos de verificação e as ferramentas para a revisão manual.';
$texto['code_13'] = 'Lista dos nomes dos elementos revistos.';
$texto['code_14'] = 'Textos de ajuda para cada item dos pontos de verificação.';
$texto['code_15'] = 'Textos para a interface do HERA.';
$texto['code_16'] = 'Textos do manual de instruções para os pontos de verificação.';
$texto['code_17'] = 'Textos das indicações na visão de página.';
$texto['code_18'] = 'Textos das Directrizes de Acessibilidade do Conteúdo na Web 1.0.';
$texto['code_19'] = 'Informação sobre os itens de cada ponto de veriicação.';
$texto['code_20'] = 'Textos de outras páginas.';
$texto['thanks_h1'] = 'Obrigado pela sua doacção!';
$texto['thanks_a'] = 'Obrigado pelo seu apoio. A sua transacção foi finalizada e enviámos-lhe um recibo da sua doaçao por correio electrónico. Pode aceder à sua conta, www.paypal.com/, para ver os detalhes desta transacção.';
$texto['thanks_b'] = 'A sua contribuição ajudará a continuarmos a oferecer ferramentas de qualidade e gratuitas para todos. Com o seu apoio poderemos continuar a melhorar e a manter a presente ferramenta. Desta forma, você contribui, directamente, para que todos os dias, a Sociedade da Informação seja um pouco mais acessível e inclusiva para todos. ';
$texto['thanks_c'] = 'A sua doacção pode permanecer no anonimato ou, se o desejar, pode enviar uma mensagem a <a href="mailto:donantes@sidar.org">donantes@sidar.org</a> com cópia da transacção da doação e publicaremos os seus dados na <a href="http://www.sidar.org/donatable.php">Tabela de Doadores</a>.';
?>
